FROM golang:1.25.6-alpine AS builder

WORKDIR /usr/src/app/template
COPY template/ ./
RUN go mod tidy && CGO_ENABLED=0 go build -o /usr/src/app/bin/template .

FROM scratch

COPY --from=alpine:latest /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /usr/src/app/bin/template /app/service
CMD ["/app/service"]
