FROM postgres:18.2-alpine3.23

RUN apk update && apk upgrade --no-cache \
    && apk add --no-cache postgresql-contrib postgresql-client

COPY postgres/init.sh /docker-entrypoint-initdb.d/init.sh
RUN chmod +x /docker-entrypoint-initdb.d/init.sh

CMD ["postgres"]