services:
  # Auth Service
  devis-auth:
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: devis-auth
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_NAME: auth
      PROJECT: auth
      TZ: Europe/Paris
    depends_on:
      - postgres
    secrets:
      - db_password
  devis-devis:
    build: .
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: devis-auth
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_NAME: auth
      PROJECT: devis
      TZ: Europe/Paris
    depends_on:
      - postgres
    secrets:
      - db_password
  postgres:
    image: postgres:18.2-alpine3.23
    restart: unless-stopped
    environment:
      POSTGRES_USER: devis-auth
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: auth
      TZ: Europe/Paris
    volumes:
      - postgres:/var/lib/postgresql/data
    secrets:
      - db_password
  adminer:
    image: adminer:5.4.2
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      - postgres
secrets:
  db_password:
    file: secrets/postgres_pswd.txt
volumes:
  postgres:
