services:
  # Auth Service
  devis-auth:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: auth
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: devis-auth
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_NAME: auth
      TZ: Europe/Paris
    depends_on:
      - postgres
    secrets:
      - db_password
  devis-quote:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: quote
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: devis-quote
      DB_PASSWORD_FILE: /run/secrets/db_password
      DB_NAME: quote
      TZ: Europe/Paris
    depends_on:
      - postgres
    secrets:
      - db_password
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: devis-auth
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: auth
      TZ: Europe/Paris
    volumes:
      - postgres:/var/lib/postgresql/data
    secrets:
      - db_password
secrets:
  db_password:
    file: secrets/postgres_pswd.txt
volumes:
  postgres:
