// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: invoice.proto

package invoice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenericResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericResponse) Reset() {
	*x = GenericResponse{}
	mi := &file_invoice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericResponse) ProtoMessage() {}

func (x *GenericResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericResponse.ProtoReflect.Descriptor instead.
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return file_invoice_proto_rawDescGZIP(), []int{0}
}

func (x *GenericResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenericResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type ValidationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_invoice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_invoice_proto_rawDescGZIP(), []int{1}
}

func (x *ValidationError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateInvoiceFromScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ScheduleId    string                 `protobuf:"bytes,2,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	MonthIndexes  []int32                `protobuf:"varint,3,rep,packed,name=month_indexes,json=monthIndexes,proto3" json:"month_indexes,omitempty"`
	SaleDate      string                 `protobuf:"bytes,4,opt,name=sale_date,json=saleDate,proto3" json:"sale_date,omitempty"`       // YYYY-MM-DD, optional (defaults to issue date)
	DueInDays     int32                  `protobuf:"varint,5,opt,name=due_in_days,json=dueInDays,proto3" json:"due_in_days,omitempty"` // optional (defaults to 30)
	IssueNow      bool                   `protobuf:"varint,6,opt,name=issue_now,json=issueNow,proto3" json:"issue_now,omitempty"`      // if true, issue immediately after creation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvoiceFromScheduleRequest) Reset() {
	*x = CreateInvoiceFromScheduleRequest{}
	mi := &file_invoice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceFromScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceFromScheduleRequest) ProtoMessage() {}

func (x *CreateInvoiceFromScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceFromScheduleRequest.ProtoReflect.Descriptor instead.
func (*CreateInvoiceFromScheduleRequest) Descriptor() ([]byte, []int) {
	return file_invoice_proto_rawDescGZIP(), []int{2}
}

func (x *CreateInvoiceFromScheduleRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateInvoiceFromScheduleRequest) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *CreateInvoiceFromScheduleRequest) GetMonthIndexes() []int32 {
	if x != nil {
		return x.MonthIndexes
	}
	return nil
}

func (x *CreateInvoiceFromScheduleRequest) GetSaleDate() string {
	if x != nil {
		return x.SaleDate
	}
	return ""
}

func (x *CreateInvoiceFromScheduleRequest) GetDueInDays() int32 {
	if x != nil {
		return x.DueInDays
	}
	return 0
}

func (x *CreateInvoiceFromScheduleRequest) GetIssueNow() bool {
	if x != nil {
		return x.IssueNow
	}
	return false
}

type CreateInvoiceFromQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuoteId       string                 `protobuf:"bytes,2,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	SaleDate      string                 `protobuf:"bytes,3,opt,name=sale_date,json=saleDate,proto3" json:"sale_date,omitempty"`
	DueInDays     int32                  `protobuf:"varint,4,opt,name=due_in_days,json=dueInDays,proto3" json:"due_in_days,omitempty"`
	IssueNow      bool                   `protobuf:"varint,5,opt,name=issue_now,json=issueNow,proto3" json:"issue_now,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvoiceFromQuoteRequest) Reset() {
	*x = CreateInvoiceFromQuoteRequest{}
	mi := &file_invoice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceFromQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceFromQuoteRequest) ProtoMessage() {}

func (x *CreateInvoiceFromQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceFromQuoteRequest.ProtoReflect.Descriptor instead.
func (*CreateInvoiceFromQuoteRequest) Descriptor() ([]byte, []int) {
	return file_invoice_proto_rawDescGZIP(), []int{3}
}

func (x *CreateInvoiceFromQuoteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateInvoiceFromQuoteRequest) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *CreateInvoiceFromQuoteRequest) GetSaleDate() string {
	if x != nil {
		return x.SaleDate
	}
	return ""
}

func (x *CreateInvoiceFromQuoteRequest) GetDueInDays() int32 {
	if x != nil {
		return x.DueInDays
	}
	return 0
}

func (x *CreateInvoiceFromQuoteRequest) GetIssueNow() bool {
	if x != nil {
		return x.IssueNow
	}
	return false
}

type CreateInvoiceResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code             int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	InvoiceId        string                 `protobuf:"bytes,3,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	InvoiceNumber    string                 `protobuf:"bytes,4,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"` // populated only when issued
	ValidationErrors []*ValidationError     `protobuf:"bytes,5,rep,name=validation_errors,json=validationErrors,proto3" json:"validation_errors,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateInvoiceResponse) Reset() {
	*x = CreateInvoiceResponse{}
	mi := &file_invoice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvoiceResponse) ProtoMessage() {}

func (x *CreateInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvoiceResponse.ProtoReflect.Descriptor instead.
func (*CreateInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_invoice_proto_rawDescGZIP(), []int{4}
}

func (x *CreateInvoiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateInvoiceResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateInvoiceResponse) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *CreateInvoiceResponse) GetInvoiceNumber() string {
	if x != nil {
		return x.InvoiceNumber
	}
	return ""
}

func (x *CreateInvoiceResponse) GetValidationErrors() []*ValidationError {
	if x != nil {
		return x.ValidationErrors
	}
	return nil
}

type IssueInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueInvoiceRequest) Reset() {
	*x = IssueInvoiceRequest{}
	mi := &file_invoice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueInvoiceRequest) ProtoMessage() {}

func (x *IssueInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueInvoiceRequest.ProtoReflect.Descriptor instead.
func (*IssueInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_invoice_proto_rawDescGZIP(), []int{5}
}

func (x *IssueInvoiceRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *IssueInvoiceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type CancelInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelInvoiceRequest) Reset() {
	*x = CancelInvoiceRequest{}
	mi := &file_invoice_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelInvoiceRequest) ProtoMessage() {}

func (x *CancelInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelInvoiceRequest.ProtoReflect.Descriptor instead.
func (*CancelInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_invoice_proto_rawDescGZIP(), []int{6}
}

func (x *CancelInvoiceRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *CancelInvoiceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type MarkInvoicePaidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkInvoicePaidRequest) Reset() {
	*x = MarkInvoicePaidRequest{}
	mi := &file_invoice_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkInvoicePaidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkInvoicePaidRequest) ProtoMessage() {}

func (x *MarkInvoicePaidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkInvoicePaidRequest.ProtoReflect.Descriptor instead.
func (*MarkInvoicePaidRequest) Descriptor() ([]byte, []int) {
	return file_invoice_proto_rawDescGZIP(), []int{7}
}

func (x *MarkInvoicePaidRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *MarkInvoicePaidRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetInvoiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceRequest) Reset() {
	*x = GetInvoiceRequest{}
	mi := &file_invoice_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceRequest) ProtoMessage() {}

func (x *GetInvoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceRequest.ProtoReflect.Descriptor instead.
func (*GetInvoiceRequest) Descriptor() ([]byte, []int) {
	return file_invoice_proto_rawDescGZIP(), []int{8}
}

func (x *GetInvoiceRequest) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *GetInvoiceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type InvoiceParty struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Company          string                 `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	FirstName        string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName         string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Siren            string                 `protobuf:"bytes,4,opt,name=siren,proto3" json:"siren,omitempty"`
	Vat              string                 `protobuf:"bytes,5,opt,name=vat,proto3" json:"vat,omitempty"`
	Email            string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phone            string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	LogoUrl          string                 `protobuf:"bytes,8,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`
	Street           string                 `protobuf:"bytes,9,opt,name=street,proto3" json:"street,omitempty"`
	AdditionalStreet string                 `protobuf:"bytes,10,opt,name=additional_street,json=additionalStreet,proto3" json:"additional_street,omitempty"`
	ZipCode          string                 `protobuf:"bytes,11,opt,name=zip_code,json=zipCode,proto3" json:"zip_code,omitempty"`
	City             string                 `protobuf:"bytes,12,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InvoiceParty) Reset() {
	*x = InvoiceParty{}
	mi := &file_invoice_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceParty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceParty) ProtoMessage() {}

func (x *InvoiceParty) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceParty.ProtoReflect.Descriptor instead.
func (*InvoiceParty) Descriptor() ([]byte, []int) {
	return file_invoice_proto_rawDescGZIP(), []int{9}
}

func (x *InvoiceParty) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *InvoiceParty) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *InvoiceParty) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *InvoiceParty) GetSiren() string {
	if x != nil {
		return x.Siren
	}
	return ""
}

func (x *InvoiceParty) GetVat() string {
	if x != nil {
		return x.Vat
	}
	return ""
}

func (x *InvoiceParty) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InvoiceParty) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *InvoiceParty) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

func (x *InvoiceParty) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *InvoiceParty) GetAdditionalStreet() string {
	if x != nil {
		return x.AdditionalStreet
	}
	return ""
}

func (x *InvoiceParty) GetZipCode() string {
	if x != nil {
		return x.ZipCode
	}
	return ""
}

func (x *InvoiceParty) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type InvoiceLine struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QuoteLineId    string                 `protobuf:"bytes,1,opt,name=quote_line_id,json=quoteLineId,proto3" json:"quote_line_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Unit           string                 `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	Quantity       string                 `protobuf:"bytes,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPriceCents int64                  `protobuf:"varint,5,opt,name=unit_price_cents,json=unitPriceCents,proto3" json:"unit_price_cents,omitempty"`
	LineHtCents    int64                  `protobuf:"varint,6,opt,name=line_ht_cents,json=lineHtCents,proto3" json:"line_ht_cents,omitempty"`
	TaxId          int32                  `protobuf:"varint,7,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	TaxRate        string                 `protobuf:"bytes,8,opt,name=tax_rate,json=taxRate,proto3" json:"tax_rate,omitempty"`
	TaxLabel       string                 `protobuf:"bytes,9,opt,name=tax_label,json=taxLabel,proto3" json:"tax_label,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InvoiceLine) Reset() {
	*x = InvoiceLine{}
	mi := &file_invoice_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceLine) ProtoMessage() {}

func (x *InvoiceLine) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceLine.ProtoReflect.Descriptor instead.
func (*InvoiceLine) Descriptor() ([]byte, []int) {
	return file_invoice_proto_rawDescGZIP(), []int{10}
}

func (x *InvoiceLine) GetQuoteLineId() string {
	if x != nil {
		return x.QuoteLineId
	}
	return ""
}

func (x *InvoiceLine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InvoiceLine) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *InvoiceLine) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *InvoiceLine) GetUnitPriceCents() int64 {
	if x != nil {
		return x.UnitPriceCents
	}
	return 0
}

func (x *InvoiceLine) GetLineHtCents() int64 {
	if x != nil {
		return x.LineHtCents
	}
	return 0
}

func (x *InvoiceLine) GetTaxId() int32 {
	if x != nil {
		return x.TaxId
	}
	return 0
}

func (x *InvoiceLine) GetTaxRate() string {
	if x != nil {
		return x.TaxRate
	}
	return ""
}

func (x *InvoiceLine) GetTaxLabel() string {
	if x != nil {
		return x.TaxLabel
	}
	return ""
}

type InvoiceVatLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaxRate       string                 `protobuf:"bytes,1,opt,name=tax_rate,json=taxRate,proto3" json:"tax_rate,omitempty"`
	BaseHtCents   int64                  `protobuf:"varint,2,opt,name=base_ht_cents,json=baseHtCents,proto3" json:"base_ht_cents,omitempty"`
	VatCents      int64                  `protobuf:"varint,3,opt,name=vat_cents,json=vatCents,proto3" json:"vat_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceVatLine) Reset() {
	*x = InvoiceVatLine{}
	mi := &file_invoice_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceVatLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceVatLine) ProtoMessage() {}

func (x *InvoiceVatLine) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceVatLine.ProtoReflect.Descriptor instead.
func (*InvoiceVatLine) Descriptor() ([]byte, []int) {
	return file_invoice_proto_rawDescGZIP(), []int{11}
}

func (x *InvoiceVatLine) GetTaxRate() string {
	if x != nil {
		return x.TaxRate
	}
	return ""
}

func (x *InvoiceVatLine) GetBaseHtCents() int64 {
	if x != nil {
		return x.BaseHtCents
	}
	return 0
}

func (x *InvoiceVatLine) GetVatCents() int64 {
	if x != nil {
		return x.VatCents
	}
	return 0
}

type InvoiceDetails struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId          string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuoteId            string                 `protobuf:"bytes,3,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	ScheduleId         string                 `protobuf:"bytes,4,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	BilledMonthIndexes []int32                `protobuf:"varint,5,rep,packed,name=billed_month_indexes,json=billedMonthIndexes,proto3" json:"billed_month_indexes,omitempty"`
	Status             string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	InvoiceNumber      string                 `protobuf:"bytes,7,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	IssuedAt           string                 `protobuf:"bytes,8,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	SaleDate           string                 `protobuf:"bytes,9,opt,name=sale_date,json=saleDate,proto3" json:"sale_date,omitempty"`
	DueDate            string                 `protobuf:"bytes,10,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	Issuer             *InvoiceParty          `protobuf:"bytes,11,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Client             *InvoiceParty          `protobuf:"bytes,12,opt,name=client,proto3" json:"client,omitempty"`
	Lines              []*InvoiceLine         `protobuf:"bytes,13,rep,name=lines,proto3" json:"lines,omitempty"`
	VatBreakdown       []*InvoiceVatLine      `protobuf:"bytes,14,rep,name=vat_breakdown,json=vatBreakdown,proto3" json:"vat_breakdown,omitempty"`
	TotalHtCents       int64                  `protobuf:"varint,15,opt,name=total_ht_cents,json=totalHtCents,proto3" json:"total_ht_cents,omitempty"`
	TotalVatCents      int64                  `protobuf:"varint,16,opt,name=total_vat_cents,json=totalVatCents,proto3" json:"total_vat_cents,omitempty"`
	TotalTtcCents      int64                  `protobuf:"varint,17,opt,name=total_ttc_cents,json=totalTtcCents,proto3" json:"total_ttc_cents,omitempty"`
	VatExempt          bool                   `protobuf:"varint,18,opt,name=vat_exempt,json=vatExempt,proto3" json:"vat_exempt,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InvoiceDetails) Reset() {
	*x = InvoiceDetails{}
	mi := &file_invoice_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceDetails) ProtoMessage() {}

func (x *InvoiceDetails) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceDetails.ProtoReflect.Descriptor instead.
func (*InvoiceDetails) Descriptor() ([]byte, []int) {
	return file_invoice_proto_rawDescGZIP(), []int{12}
}

func (x *InvoiceDetails) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *InvoiceDetails) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *InvoiceDetails) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *InvoiceDetails) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *InvoiceDetails) GetBilledMonthIndexes() []int32 {
	if x != nil {
		return x.BilledMonthIndexes
	}
	return nil
}

func (x *InvoiceDetails) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InvoiceDetails) GetInvoiceNumber() string {
	if x != nil {
		return x.InvoiceNumber
	}
	return ""
}

func (x *InvoiceDetails) GetIssuedAt() string {
	if x != nil {
		return x.IssuedAt
	}
	return ""
}

func (x *InvoiceDetails) GetSaleDate() string {
	if x != nil {
		return x.SaleDate
	}
	return ""
}

func (x *InvoiceDetails) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *InvoiceDetails) GetIssuer() *InvoiceParty {
	if x != nil {
		return x.Issuer
	}
	return nil
}

func (x *InvoiceDetails) GetClient() *InvoiceParty {
	if x != nil {
		return x.Client
	}
	return nil
}

func (x *InvoiceDetails) GetLines() []*InvoiceLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *InvoiceDetails) GetVatBreakdown() []*InvoiceVatLine {
	if x != nil {
		return x.VatBreakdown
	}
	return nil
}

func (x *InvoiceDetails) GetTotalHtCents() int64 {
	if x != nil {
		return x.TotalHtCents
	}
	return 0
}

func (x *InvoiceDetails) GetTotalVatCents() int64 {
	if x != nil {
		return x.TotalVatCents
	}
	return 0
}

func (x *InvoiceDetails) GetTotalTtcCents() int64 {
	if x != nil {
		return x.TotalTtcCents
	}
	return 0
}

func (x *InvoiceDetails) GetVatExempt() bool {
	if x != nil {
		return x.VatExempt
	}
	return false
}

type GetInvoiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Invoice       *InvoiceDetails        `protobuf:"bytes,3,opt,name=invoice,proto3" json:"invoice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInvoiceResponse) Reset() {
	*x = GetInvoiceResponse{}
	mi := &file_invoice_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInvoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInvoiceResponse) ProtoMessage() {}

func (x *GetInvoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInvoiceResponse.ProtoReflect.Descriptor instead.
func (*GetInvoiceResponse) Descriptor() ([]byte, []int) {
	return file_invoice_proto_rawDescGZIP(), []int{13}
}

func (x *GetInvoiceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetInvoiceResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetInvoiceResponse) GetInvoice() *InvoiceDetails {
	if x != nil {
		return x.Invoice
	}
	return nil
}

type ListInvoicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	QuoteId       string                 `protobuf:"bytes,2,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvoicesRequest) Reset() {
	*x = ListInvoicesRequest{}
	mi := &file_invoice_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvoicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvoicesRequest) ProtoMessage() {}

func (x *ListInvoicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvoicesRequest.ProtoReflect.Descriptor instead.
func (*ListInvoicesRequest) Descriptor() ([]byte, []int) {
	return file_invoice_proto_rawDescGZIP(), []int{14}
}

func (x *ListInvoicesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListInvoicesRequest) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

type InvoiceSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvoiceId     string                 `protobuf:"bytes,1,opt,name=invoice_id,json=invoiceId,proto3" json:"invoice_id,omitempty"`
	InvoiceNumber string                 `protobuf:"bytes,2,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	QuoteId       string                 `protobuf:"bytes,4,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	ScheduleId    string                 `protobuf:"bytes,5,opt,name=schedule_id,json=scheduleId,proto3" json:"schedule_id,omitempty"`
	IssuedAt      string                 `protobuf:"bytes,6,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	DueDate       string                 `protobuf:"bytes,7,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	TotalTtcCents int64                  `protobuf:"varint,8,opt,name=total_ttc_cents,json=totalTtcCents,proto3" json:"total_ttc_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvoiceSummary) Reset() {
	*x = InvoiceSummary{}
	mi := &file_invoice_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvoiceSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvoiceSummary) ProtoMessage() {}

func (x *InvoiceSummary) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvoiceSummary.ProtoReflect.Descriptor instead.
func (*InvoiceSummary) Descriptor() ([]byte, []int) {
	return file_invoice_proto_rawDescGZIP(), []int{15}
}

func (x *InvoiceSummary) GetInvoiceId() string {
	if x != nil {
		return x.InvoiceId
	}
	return ""
}

func (x *InvoiceSummary) GetInvoiceNumber() string {
	if x != nil {
		return x.InvoiceNumber
	}
	return ""
}

func (x *InvoiceSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InvoiceSummary) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *InvoiceSummary) GetScheduleId() string {
	if x != nil {
		return x.ScheduleId
	}
	return ""
}

func (x *InvoiceSummary) GetIssuedAt() string {
	if x != nil {
		return x.IssuedAt
	}
	return ""
}

func (x *InvoiceSummary) GetDueDate() string {
	if x != nil {
		return x.DueDate
	}
	return ""
}

func (x *InvoiceSummary) GetTotalTtcCents() int64 {
	if x != nil {
		return x.TotalTtcCents
	}
	return 0
}

type ListInvoicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Invoices      []*InvoiceSummary      `protobuf:"bytes,3,rep,name=invoices,proto3" json:"invoices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvoicesResponse) Reset() {
	*x = ListInvoicesResponse{}
	mi := &file_invoice_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvoicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvoicesResponse) ProtoMessage() {}

func (x *ListInvoicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvoicesResponse.ProtoReflect.Descriptor instead.
func (*ListInvoicesResponse) Descriptor() ([]byte, []int) {
	return file_invoice_proto_rawDescGZIP(), []int{16}
}

func (x *ListInvoicesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListInvoicesResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListInvoicesResponse) GetInvoices() []*InvoiceSummary {
	if x != nil {
		return x.Invoices
	}
	return nil
}

var File_invoice_proto protoreflect.FileDescriptor

const file_invoice_proto_rawDesc = "" +
	"\n" +
	"\rinvoice.proto\x12\ainvoice\"?\n" +
	"\x0fGenericResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"A\n" +
	"\x0fValidationError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xdb\x01\n" +
	" CreateInvoiceFromScheduleRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vschedule_id\x18\x02 \x01(\tR\n" +
	"scheduleId\x12#\n" +
	"\rmonth_indexes\x18\x03 \x03(\x05R\fmonthIndexes\x12\x1b\n" +
	"\tsale_date\x18\x04 \x01(\tR\bsaleDate\x12\x1e\n" +
	"\vdue_in_days\x18\x05 \x01(\x05R\tdueInDays\x12\x1b\n" +
	"\tissue_now\x18\x06 \x01(\bR\bissueNow\"\xad\x01\n" +
	"\x1dCreateInvoiceFromQuoteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bquote_id\x18\x02 \x01(\tR\aquoteId\x12\x1b\n" +
	"\tsale_date\x18\x03 \x01(\tR\bsaleDate\x12\x1e\n" +
	"\vdue_in_days\x18\x04 \x01(\x05R\tdueInDays\x12\x1b\n" +
	"\tissue_now\x18\x05 \x01(\bR\bissueNow\"\xd2\x01\n" +
	"\x15CreateInvoiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x03 \x01(\tR\tinvoiceId\x12%\n" +
	"\x0einvoice_number\x18\x04 \x01(\tR\rinvoiceNumber\x12E\n" +
	"\x11validation_errors\x18\x05 \x03(\v2\x18.invoice.ValidationErrorR\x10validationErrors\"M\n" +
	"\x13IssueInvoiceRequest\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"N\n" +
	"\x14CancelInvoiceRequest\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"P\n" +
	"\x16MarkInvoicePaidRequest\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"K\n" +
	"\x11GetInvoiceRequest\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xc7\x02\n" +
	"\fInvoiceParty\x12\x18\n" +
	"\acompany\x18\x01 \x01(\tR\acompany\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x14\n" +
	"\x05siren\x18\x04 \x01(\tR\x05siren\x12\x10\n" +
	"\x03vat\x18\x05 \x01(\tR\x03vat\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12\x19\n" +
	"\blogo_url\x18\b \x01(\tR\alogoUrl\x12\x16\n" +
	"\x06street\x18\t \x01(\tR\x06street\x12+\n" +
	"\x11additional_street\x18\n" +
	" \x01(\tR\x10additionalStreet\x12\x19\n" +
	"\bzip_code\x18\v \x01(\tR\azipCode\x12\x12\n" +
	"\x04city\x18\f \x01(\tR\x04city\"\x92\x02\n" +
	"\vInvoiceLine\x12\"\n" +
	"\rquote_line_id\x18\x01 \x01(\tR\vquoteLineId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\tR\bquantity\x12(\n" +
	"\x10unit_price_cents\x18\x05 \x01(\x03R\x0eunitPriceCents\x12\"\n" +
	"\rline_ht_cents\x18\x06 \x01(\x03R\vlineHtCents\x12\x15\n" +
	"\x06tax_id\x18\a \x01(\x05R\x05taxId\x12\x19\n" +
	"\btax_rate\x18\b \x01(\tR\ataxRate\x12\x1b\n" +
	"\ttax_label\x18\t \x01(\tR\btaxLabel\"l\n" +
	"\x0eInvoiceVatLine\x12\x19\n" +
	"\btax_rate\x18\x01 \x01(\tR\ataxRate\x12\"\n" +
	"\rbase_ht_cents\x18\x02 \x01(\x03R\vbaseHtCents\x12\x1b\n" +
	"\tvat_cents\x18\x03 \x01(\x03R\bvatCents\"\xa7\x05\n" +
	"\x0eInvoiceDetails\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bquote_id\x18\x03 \x01(\tR\aquoteId\x12\x1f\n" +
	"\vschedule_id\x18\x04 \x01(\tR\n" +
	"scheduleId\x120\n" +
	"\x14billed_month_indexes\x18\x05 \x03(\x05R\x12billedMonthIndexes\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12%\n" +
	"\x0einvoice_number\x18\a \x01(\tR\rinvoiceNumber\x12\x1b\n" +
	"\tissued_at\x18\b \x01(\tR\bissuedAt\x12\x1b\n" +
	"\tsale_date\x18\t \x01(\tR\bsaleDate\x12\x19\n" +
	"\bdue_date\x18\n" +
	" \x01(\tR\adueDate\x12-\n" +
	"\x06issuer\x18\v \x01(\v2\x15.invoice.InvoicePartyR\x06issuer\x12-\n" +
	"\x06client\x18\f \x01(\v2\x15.invoice.InvoicePartyR\x06client\x12*\n" +
	"\x05lines\x18\r \x03(\v2\x14.invoice.InvoiceLineR\x05lines\x12<\n" +
	"\rvat_breakdown\x18\x0e \x03(\v2\x17.invoice.InvoiceVatLineR\fvatBreakdown\x12$\n" +
	"\x0etotal_ht_cents\x18\x0f \x01(\x03R\ftotalHtCents\x12&\n" +
	"\x0ftotal_vat_cents\x18\x10 \x01(\x03R\rtotalVatCents\x12&\n" +
	"\x0ftotal_ttc_cents\x18\x11 \x01(\x03R\rtotalTtcCents\x12\x1d\n" +
	"\n" +
	"vat_exempt\x18\x12 \x01(\bR\tvatExempt\"u\n" +
	"\x12GetInvoiceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x121\n" +
	"\ainvoice\x18\x03 \x01(\v2\x17.invoice.InvoiceDetailsR\ainvoice\"I\n" +
	"\x13ListInvoicesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bquote_id\x18\x02 \x01(\tR\aquoteId\"\x8a\x02\n" +
	"\x0eInvoiceSummary\x12\x1d\n" +
	"\n" +
	"invoice_id\x18\x01 \x01(\tR\tinvoiceId\x12%\n" +
	"\x0einvoice_number\x18\x02 \x01(\tR\rinvoiceNumber\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x19\n" +
	"\bquote_id\x18\x04 \x01(\tR\aquoteId\x12\x1f\n" +
	"\vschedule_id\x18\x05 \x01(\tR\n" +
	"scheduleId\x12\x1b\n" +
	"\tissued_at\x18\x06 \x01(\tR\bissuedAt\x12\x19\n" +
	"\bdue_date\x18\a \x01(\tR\adueDate\x12&\n" +
	"\x0ftotal_ttc_cents\x18\b \x01(\x03R\rtotalTtcCents\"y\n" +
	"\x14ListInvoicesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x123\n" +
	"\binvoices\x18\x03 \x03(\v2\x17.invoice.InvoiceSummaryR\binvoices2\xd4\x04\n" +
	"\x0eInvoiceService\x12f\n" +
	"\x19CreateInvoiceFromSchedule\x12).invoice.CreateInvoiceFromScheduleRequest\x1a\x1e.invoice.CreateInvoiceResponse\x12`\n" +
	"\x16CreateInvoiceFromQuote\x12&.invoice.CreateInvoiceFromQuoteRequest\x1a\x1e.invoice.CreateInvoiceResponse\x12L\n" +
	"\fIssueInvoice\x12\x1c.invoice.IssueInvoiceRequest\x1a\x1e.invoice.CreateInvoiceResponse\x12H\n" +
	"\rCancelInvoice\x12\x1d.invoice.CancelInvoiceRequest\x1a\x18.invoice.GenericResponse\x12L\n" +
	"\x0fMarkInvoicePaid\x12\x1f.invoice.MarkInvoicePaidRequest\x1a\x18.invoice.GenericResponse\x12E\n" +
	"\n" +
	"GetInvoice\x12\x1a.invoice.GetInvoiceRequest\x1a\x1b.invoice.GetInvoiceResponse\x12K\n" +
	"\fListInvoices\x12\x1c.invoice.ListInvoicesRequest\x1a\x1d.invoice.ListInvoicesResponseB\x11Z\x0fgateway/invoiceb\x06proto3"

var (
	file_invoice_proto_rawDescOnce sync.Once
	file_invoice_proto_rawDescData []byte
)

func file_invoice_proto_rawDescGZIP() []byte {
	file_invoice_proto_rawDescOnce.Do(func() {
		file_invoice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_invoice_proto_rawDesc), len(file_invoice_proto_rawDesc)))
	})
	return file_invoice_proto_rawDescData
}

var file_invoice_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_invoice_proto_goTypes = []any{
	(*GenericResponse)(nil),                  // 0: invoice.GenericResponse
	(*ValidationError)(nil),                  // 1: invoice.ValidationError
	(*CreateInvoiceFromScheduleRequest)(nil), // 2: invoice.CreateInvoiceFromScheduleRequest
	(*CreateInvoiceFromQuoteRequest)(nil),    // 3: invoice.CreateInvoiceFromQuoteRequest
	(*CreateInvoiceResponse)(nil),            // 4: invoice.CreateInvoiceResponse
	(*IssueInvoiceRequest)(nil),              // 5: invoice.IssueInvoiceRequest
	(*CancelInvoiceRequest)(nil),             // 6: invoice.CancelInvoiceRequest
	(*MarkInvoicePaidRequest)(nil),           // 7: invoice.MarkInvoicePaidRequest
	(*GetInvoiceRequest)(nil),                // 8: invoice.GetInvoiceRequest
	(*InvoiceParty)(nil),                     // 9: invoice.InvoiceParty
	(*InvoiceLine)(nil),                      // 10: invoice.InvoiceLine
	(*InvoiceVatLine)(nil),                   // 11: invoice.InvoiceVatLine
	(*InvoiceDetails)(nil),                   // 12: invoice.InvoiceDetails
	(*GetInvoiceResponse)(nil),               // 13: invoice.GetInvoiceResponse
	(*ListInvoicesRequest)(nil),              // 14: invoice.ListInvoicesRequest
	(*InvoiceSummary)(nil),                   // 15: invoice.InvoiceSummary
	(*ListInvoicesResponse)(nil),             // 16: invoice.ListInvoicesResponse
}
var file_invoice_proto_depIdxs = []int32{
	1,  // 0: invoice.CreateInvoiceResponse.validation_errors:type_name -> invoice.ValidationError
	9,  // 1: invoice.InvoiceDetails.issuer:type_name -> invoice.InvoiceParty
	9,  // 2: invoice.InvoiceDetails.client:type_name -> invoice.InvoiceParty
	10, // 3: invoice.InvoiceDetails.lines:type_name -> invoice.InvoiceLine
	11, // 4: invoice.InvoiceDetails.vat_breakdown:type_name -> invoice.InvoiceVatLine
	12, // 5: invoice.GetInvoiceResponse.invoice:type_name -> invoice.InvoiceDetails
	15, // 6: invoice.ListInvoicesResponse.invoices:type_name -> invoice.InvoiceSummary
	2,  // 7: invoice.InvoiceService.CreateInvoiceFromSchedule:input_type -> invoice.CreateInvoiceFromScheduleRequest
	3,  // 8: invoice.InvoiceService.CreateInvoiceFromQuote:input_type -> invoice.CreateInvoiceFromQuoteRequest
	5,  // 9: invoice.InvoiceService.IssueInvoice:input_type -> invoice.IssueInvoiceRequest
	6,  // 10: invoice.InvoiceService.CancelInvoice:input_type -> invoice.CancelInvoiceRequest
	7,  // 11: invoice.InvoiceService.MarkInvoicePaid:input_type -> invoice.MarkInvoicePaidRequest
	8,  // 12: invoice.InvoiceService.GetInvoice:input_type -> invoice.GetInvoiceRequest
	14, // 13: invoice.InvoiceService.ListInvoices:input_type -> invoice.ListInvoicesRequest
	4,  // 14: invoice.InvoiceService.CreateInvoiceFromSchedule:output_type -> invoice.CreateInvoiceResponse
	4,  // 15: invoice.InvoiceService.CreateInvoiceFromQuote:output_type -> invoice.CreateInvoiceResponse
	4,  // 16: invoice.InvoiceService.IssueInvoice:output_type -> invoice.CreateInvoiceResponse
	0,  // 17: invoice.InvoiceService.CancelInvoice:output_type -> invoice.GenericResponse
	0,  // 18: invoice.InvoiceService.MarkInvoicePaid:output_type -> invoice.GenericResponse
	13, // 19: invoice.InvoiceService.GetInvoice:output_type -> invoice.GetInvoiceResponse
	16, // 20: invoice.InvoiceService.ListInvoices:output_type -> invoice.ListInvoicesResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_invoice_proto_init() }
func file_invoice_proto_init() {
	if File_invoice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_invoice_proto_rawDesc), len(file_invoice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_invoice_proto_goTypes,
		DependencyIndexes: file_invoice_proto_depIdxs,
		MessageInfos:      file_invoice_proto_msgTypes,
	}.Build()
	File_invoice_proto = out.File
	file_invoice_proto_goTypes = nil
	file_invoice_proto_depIdxs = nil
}
