// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: services/grpc/email.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmailService_SendQuoteEmail_FullMethodName    = "/email.EmailService/SendQuoteEmail"
	EmailService_SendScheduleEmail_FullMethodName = "/email.EmailService/SendScheduleEmail"
	EmailService_SendGenericEmail_FullMethodName  = "/email.EmailService/SendGenericEmail"
	EmailService_GetEmailLogs_FullMethodName      = "/email.EmailService/GetEmailLogs"
	EmailService_TrackEmailEvent_FullMethodName   = "/email.EmailService/TrackEmailEvent"
)

// EmailServiceClient is the client API for EmailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmailServiceClient interface {
	SendQuoteEmail(ctx context.Context, in *SendQuoteEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error)
	SendScheduleEmail(ctx context.Context, in *SendScheduleEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error)
	SendGenericEmail(ctx context.Context, in *SendGenericEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error)
	GetEmailLogs(ctx context.Context, in *GetEmailLogsRequest, opts ...grpc.CallOption) (*GetEmailLogsResponse, error)
	TrackEmailEvent(ctx context.Context, in *TrackEmailEventRequest, opts ...grpc.CallOption) (*GenericResponse, error)
}

type emailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailServiceClient(cc grpc.ClientConnInterface) EmailServiceClient {
	return &emailServiceClient{cc}
}

func (c *emailServiceClient) SendQuoteEmail(ctx context.Context, in *SendQuoteEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendEmailResponse)
	err := c.cc.Invoke(ctx, EmailService_SendQuoteEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) SendScheduleEmail(ctx context.Context, in *SendScheduleEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendEmailResponse)
	err := c.cc.Invoke(ctx, EmailService_SendScheduleEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) SendGenericEmail(ctx context.Context, in *SendGenericEmailRequest, opts ...grpc.CallOption) (*SendEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendEmailResponse)
	err := c.cc.Invoke(ctx, EmailService_SendGenericEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) GetEmailLogs(ctx context.Context, in *GetEmailLogsRequest, opts ...grpc.CallOption) (*GetEmailLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEmailLogsResponse)
	err := c.cc.Invoke(ctx, EmailService_GetEmailLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailServiceClient) TrackEmailEvent(ctx context.Context, in *TrackEmailEventRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, EmailService_TrackEmailEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailServiceServer is the server API for EmailService service.
// All implementations must embed UnimplementedEmailServiceServer
// for forward compatibility.
type EmailServiceServer interface {
	SendQuoteEmail(context.Context, *SendQuoteEmailRequest) (*SendEmailResponse, error)
	SendScheduleEmail(context.Context, *SendScheduleEmailRequest) (*SendEmailResponse, error)
	SendGenericEmail(context.Context, *SendGenericEmailRequest) (*SendEmailResponse, error)
	GetEmailLogs(context.Context, *GetEmailLogsRequest) (*GetEmailLogsResponse, error)
	TrackEmailEvent(context.Context, *TrackEmailEventRequest) (*GenericResponse, error)
	mustEmbedUnimplementedEmailServiceServer()
}

// UnimplementedEmailServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmailServiceServer struct{}

func (UnimplementedEmailServiceServer) SendQuoteEmail(context.Context, *SendQuoteEmailRequest) (*SendEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendQuoteEmail not implemented")
}
func (UnimplementedEmailServiceServer) SendScheduleEmail(context.Context, *SendScheduleEmailRequest) (*SendEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendScheduleEmail not implemented")
}
func (UnimplementedEmailServiceServer) SendGenericEmail(context.Context, *SendGenericEmailRequest) (*SendEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendGenericEmail not implemented")
}
func (UnimplementedEmailServiceServer) GetEmailLogs(context.Context, *GetEmailLogsRequest) (*GetEmailLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEmailLogs not implemented")
}
func (UnimplementedEmailServiceServer) TrackEmailEvent(context.Context, *TrackEmailEventRequest) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TrackEmailEvent not implemented")
}
func (UnimplementedEmailServiceServer) mustEmbedUnimplementedEmailServiceServer() {}
func (UnimplementedEmailServiceServer) testEmbeddedByValue()                      {}

// UnsafeEmailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailServiceServer will
// result in compilation errors.
type UnsafeEmailServiceServer interface {
	mustEmbedUnimplementedEmailServiceServer()
}

func RegisterEmailServiceServer(s grpc.ServiceRegistrar, srv EmailServiceServer) {
	// If the following call panics, it indicates UnimplementedEmailServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmailService_ServiceDesc, srv)
}

func _EmailService_SendQuoteEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendQuoteEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).SendQuoteEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailService_SendQuoteEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).SendQuoteEmail(ctx, req.(*SendQuoteEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailService_SendScheduleEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendScheduleEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).SendScheduleEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailService_SendScheduleEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).SendScheduleEmail(ctx, req.(*SendScheduleEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailService_SendGenericEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendGenericEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).SendGenericEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailService_SendGenericEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).SendGenericEmail(ctx, req.(*SendGenericEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailService_GetEmailLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEmailLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).GetEmailLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailService_GetEmailLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).GetEmailLogs(ctx, req.(*GetEmailLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailService_TrackEmailEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrackEmailEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailServiceServer).TrackEmailEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmailService_TrackEmailEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailServiceServer).TrackEmailEvent(ctx, req.(*TrackEmailEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmailService_ServiceDesc is the grpc.ServiceDesc for EmailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "email.EmailService",
	HandlerType: (*EmailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendQuoteEmail",
			Handler:    _EmailService_SendQuoteEmail_Handler,
		},
		{
			MethodName: "SendScheduleEmail",
			Handler:    _EmailService_SendScheduleEmail_Handler,
		},
		{
			MethodName: "SendGenericEmail",
			Handler:    _EmailService_SendGenericEmail_Handler,
		},
		{
			MethodName: "GetEmailLogs",
			Handler:    _EmailService_GetEmailLogs_Handler,
		},
		{
			MethodName: "TrackEmailEvent",
			Handler:    _EmailService_TrackEmailEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/grpc/email.proto",
}
