// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: quote.proto

package quote

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuoteState int32

const (
	QuoteState_QUOTE_STATE_UNSPECIFIED QuoteState = 0
	QuoteState_QUOTE_STATE_DRAFT       QuoteState = 1
	QuoteState_QUOTE_STATE_SENT        QuoteState = 2
	QuoteState_QUOTE_STATE_VALIDATED   QuoteState = 3
	QuoteState_QUOTE_STATE_DROP        QuoteState = 4
)

// Enum value maps for QuoteState.
var (
	QuoteState_name = map[int32]string{
		0: "QUOTE_STATE_UNSPECIFIED",
		1: "QUOTE_STATE_DRAFT",
		2: "QUOTE_STATE_SENT",
		3: "QUOTE_STATE_VALIDATED",
		4: "QUOTE_STATE_DROP",
	}
	QuoteState_value = map[string]int32{
		"QUOTE_STATE_UNSPECIFIED": 0,
		"QUOTE_STATE_DRAFT":       1,
		"QUOTE_STATE_SENT":        2,
		"QUOTE_STATE_VALIDATED":   3,
		"QUOTE_STATE_DROP":        4,
	}
)

func (x QuoteState) Enum() *QuoteState {
	p := new(QuoteState)
	*p = x
	return p
}

func (x QuoteState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuoteState) Descriptor() protoreflect.EnumDescriptor {
	return file_quote_proto_enumTypes[0].Descriptor()
}

func (QuoteState) Type() protoreflect.EnumType {
	return &file_quote_proto_enumTypes[0]
}

func (x QuoteState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuoteState.Descriptor instead.
func (QuoteState) EnumDescriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{0}
}

type GenericResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericResponse) Reset() {
	*x = GenericResponse{}
	mi := &file_quote_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericResponse) ProtoMessage() {}

func (x *GenericResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericResponse.ProtoReflect.Descriptor instead.
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{0}
}

func (x *GenericResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenericResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type Quote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuoteId       string                 `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Archived      bool                   `protobuf:"varint,4,opt,name=archived,proto3" json:"archived,omitempty"`
	State         QuoteState             `protobuf:"varint,5,opt,name=state,proto3,enum=quote.QuoteState" json:"state,omitempty"`
	ClientId      string                 `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AddressId     int32                  `protobuf:"varint,7,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quote) Reset() {
	*x = Quote{}
	mi := &file_quote_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quote) ProtoMessage() {}

func (x *Quote) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quote.ProtoReflect.Descriptor instead.
func (*Quote) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{1}
}

func (x *Quote) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *Quote) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Quote) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Quote) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *Quote) GetState() QuoteState {
	if x != nil {
		return x.State
	}
	return QuoteState_QUOTE_STATE_UNSPECIFIED
}

func (x *Quote) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Quote) GetAddressId() int32 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

type CreateQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AddressId     int32                  `protobuf:"varint,4,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuoteRequest) Reset() {
	*x = CreateQuoteRequest{}
	mi := &file_quote_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuoteRequest) ProtoMessage() {}

func (x *CreateQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuoteRequest.ProtoReflect.Descriptor instead.
func (*CreateQuoteRequest) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{2}
}

func (x *CreateQuoteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateQuoteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateQuoteRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateQuoteRequest) GetAddressId() int32 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

type CreateQuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	QuoteId       string                 `protobuf:"bytes,3,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuoteResponse) Reset() {
	*x = CreateQuoteResponse{}
	mi := &file_quote_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuoteResponse) ProtoMessage() {}

func (x *CreateQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuoteResponse.ProtoReflect.Descriptor instead.
func (*CreateQuoteResponse) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{3}
}

func (x *CreateQuoteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateQuoteResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateQuoteResponse) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

type GetQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuoteId       string                 `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteRequest) Reset() {
	*x = GetQuoteRequest{}
	mi := &file_quote_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteRequest) ProtoMessage() {}

func (x *GetQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteRequest.ProtoReflect.Descriptor instead.
func (*GetQuoteRequest) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{4}
}

func (x *GetQuoteRequest) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *GetQuoteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetQuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Quote         *Quote                 `protobuf:"bytes,3,opt,name=quote,proto3" json:"quote,omitempty"`
	Lines         []*QuoteLine           `protobuf:"bytes,4,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteResponse) Reset() {
	*x = GetQuoteResponse{}
	mi := &file_quote_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteResponse) ProtoMessage() {}

func (x *GetQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteResponse.ProtoReflect.Descriptor instead.
func (*GetQuoteResponse) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{5}
}

func (x *GetQuoteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetQuoteResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetQuoteResponse) GetQuote() *Quote {
	if x != nil {
		return x.Quote
	}
	return nil
}

func (x *GetQuoteResponse) GetLines() []*QuoteLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type ListQuotesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IncludeArchived bool                   `protobuf:"varint,2,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListQuotesRequest) Reset() {
	*x = ListQuotesRequest{}
	mi := &file_quote_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuotesRequest) ProtoMessage() {}

func (x *ListQuotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuotesRequest.ProtoReflect.Descriptor instead.
func (*ListQuotesRequest) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{6}
}

func (x *ListQuotesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListQuotesRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

type ListQuotesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Quotes        []*Quote               `protobuf:"bytes,3,rep,name=quotes,proto3" json:"quotes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuotesResponse) Reset() {
	*x = ListQuotesResponse{}
	mi := &file_quote_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuotesResponse) ProtoMessage() {}

func (x *ListQuotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuotesResponse.ProtoReflect.Descriptor instead.
func (*ListQuotesResponse) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{7}
}

func (x *ListQuotesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListQuotesResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListQuotesResponse) GetQuotes() []*Quote {
	if x != nil {
		return x.Quotes
	}
	return nil
}

type UpdateQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuoteId       string                 `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AddressId     int32                  `protobuf:"varint,5,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuoteRequest) Reset() {
	*x = UpdateQuoteRequest{}
	mi := &file_quote_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuoteRequest) ProtoMessage() {}

func (x *UpdateQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuoteRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuoteRequest) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateQuoteRequest) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *UpdateQuoteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateQuoteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateQuoteRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *UpdateQuoteRequest) GetAddressId() int32 {
	if x != nil {
		return x.AddressId
	}
	return 0
}

type UpdateQuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuoteResponse) Reset() {
	*x = UpdateQuoteResponse{}
	mi := &file_quote_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuoteResponse) ProtoMessage() {}

func (x *UpdateQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuoteResponse.ProtoReflect.Descriptor instead.
func (*UpdateQuoteResponse) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateQuoteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateQuoteResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type DeleteQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuoteId       string                 `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuoteRequest) Reset() {
	*x = DeleteQuoteRequest{}
	mi := &file_quote_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuoteRequest) ProtoMessage() {}

func (x *DeleteQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuoteRequest.ProtoReflect.Descriptor instead.
func (*DeleteQuoteRequest) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteQuoteRequest) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *DeleteQuoteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ArchiveQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuoteId       string                 `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveQuoteRequest) Reset() {
	*x = ArchiveQuoteRequest{}
	mi := &file_quote_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveQuoteRequest) ProtoMessage() {}

func (x *ArchiveQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveQuoteRequest.ProtoReflect.Descriptor instead.
func (*ArchiveQuoteRequest) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{11}
}

func (x *ArchiveQuoteRequest) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *ArchiveQuoteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RestoreQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuoteId       string                 `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreQuoteRequest) Reset() {
	*x = RestoreQuoteRequest{}
	mi := &file_quote_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreQuoteRequest) ProtoMessage() {}

func (x *RestoreQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreQuoteRequest.ProtoReflect.Descriptor instead.
func (*RestoreQuoteRequest) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{12}
}

func (x *RestoreQuoteRequest) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *RestoreQuoteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type TrashQuotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrashQuotesRequest) Reset() {
	*x = TrashQuotesRequest{}
	mi := &file_quote_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrashQuotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrashQuotesRequest) ProtoMessage() {}

func (x *TrashQuotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrashQuotesRequest.ProtoReflect.Descriptor instead.
func (*TrashQuotesRequest) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{13}
}

func (x *TrashQuotesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DropQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuoteId       string                 `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropQuoteRequest) Reset() {
	*x = DropQuoteRequest{}
	mi := &file_quote_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropQuoteRequest) ProtoMessage() {}

func (x *DropQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropQuoteRequest.ProtoReflect.Descriptor instead.
func (*DropQuoteRequest) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{14}
}

func (x *DropQuoteRequest) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *DropQuoteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ContinueQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuoteId       string                 `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContinueQuoteRequest) Reset() {
	*x = ContinueQuoteRequest{}
	mi := &file_quote_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueQuoteRequest) ProtoMessage() {}

func (x *ContinueQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinueQuoteRequest.ProtoReflect.Descriptor instead.
func (*ContinueQuoteRequest) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{15}
}

func (x *ContinueQuoteRequest) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *ContinueQuoteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type QuoteLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LineId        string                 `protobuf:"bytes,1,opt,name=line_id,json=lineId,proto3" json:"line_id,omitempty"`
	QuoteId       string                 `protobuf:"bytes,2,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      string                 `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Unit          string                 `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	UnitPrice     int64                  `protobuf:"varint,7,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Data          string                 `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	Position      int32                  `protobuf:"varint,9,opt,name=position,proto3" json:"position,omitempty"`
	TaxId         int32                  `protobuf:"varint,10,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteLine) Reset() {
	*x = QuoteLine{}
	mi := &file_quote_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteLine) ProtoMessage() {}

func (x *QuoteLine) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteLine.ProtoReflect.Descriptor instead.
func (*QuoteLine) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{16}
}

func (x *QuoteLine) GetLineId() string {
	if x != nil {
		return x.LineId
	}
	return ""
}

func (x *QuoteLine) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *QuoteLine) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *QuoteLine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QuoteLine) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *QuoteLine) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *QuoteLine) GetUnitPrice() int64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *QuoteLine) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *QuoteLine) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *QuoteLine) GetTaxId() int32 {
	if x != nil {
		return x.TaxId
	}
	return 0
}

type CreateQuoteLineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuoteId       string                 `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      string                 `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Unit          string                 `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	UnitPrice     int64                  `protobuf:"varint,7,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Data          string                 `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	Position      int32                  `protobuf:"varint,9,opt,name=position,proto3" json:"position,omitempty"`
	TaxId         int32                  `protobuf:"varint,10,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuoteLineRequest) Reset() {
	*x = CreateQuoteLineRequest{}
	mi := &file_quote_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuoteLineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuoteLineRequest) ProtoMessage() {}

func (x *CreateQuoteLineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuoteLineRequest.ProtoReflect.Descriptor instead.
func (*CreateQuoteLineRequest) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{17}
}

func (x *CreateQuoteLineRequest) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *CreateQuoteLineRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateQuoteLineRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateQuoteLineRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateQuoteLineRequest) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *CreateQuoteLineRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *CreateQuoteLineRequest) GetUnitPrice() int64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *CreateQuoteLineRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *CreateQuoteLineRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *CreateQuoteLineRequest) GetTaxId() int32 {
	if x != nil {
		return x.TaxId
	}
	return 0
}

type CreateQuoteLineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	LineId        string                 `protobuf:"bytes,3,opt,name=line_id,json=lineId,proto3" json:"line_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateQuoteLineResponse) Reset() {
	*x = CreateQuoteLineResponse{}
	mi := &file_quote_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateQuoteLineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateQuoteLineResponse) ProtoMessage() {}

func (x *CreateQuoteLineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateQuoteLineResponse.ProtoReflect.Descriptor instead.
func (*CreateQuoteLineResponse) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{18}
}

func (x *CreateQuoteLineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateQuoteLineResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateQuoteLineResponse) GetLineId() string {
	if x != nil {
		return x.LineId
	}
	return ""
}

type GetQuoteLineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LineId        string                 `protobuf:"bytes,1,opt,name=line_id,json=lineId,proto3" json:"line_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteLineRequest) Reset() {
	*x = GetQuoteLineRequest{}
	mi := &file_quote_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteLineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteLineRequest) ProtoMessage() {}

func (x *GetQuoteLineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteLineRequest.ProtoReflect.Descriptor instead.
func (*GetQuoteLineRequest) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{19}
}

func (x *GetQuoteLineRequest) GetLineId() string {
	if x != nil {
		return x.LineId
	}
	return ""
}

func (x *GetQuoteLineRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetQuoteLineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Line          *QuoteLine             `protobuf:"bytes,3,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQuoteLineResponse) Reset() {
	*x = GetQuoteLineResponse{}
	mi := &file_quote_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQuoteLineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuoteLineResponse) ProtoMessage() {}

func (x *GetQuoteLineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuoteLineResponse.ProtoReflect.Descriptor instead.
func (*GetQuoteLineResponse) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{20}
}

func (x *GetQuoteLineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetQuoteLineResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetQuoteLineResponse) GetLine() *QuoteLine {
	if x != nil {
		return x.Line
	}
	return nil
}

type ListQuoteLinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuoteId       string                 `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuoteLinesRequest) Reset() {
	*x = ListQuoteLinesRequest{}
	mi := &file_quote_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuoteLinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuoteLinesRequest) ProtoMessage() {}

func (x *ListQuoteLinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuoteLinesRequest.ProtoReflect.Descriptor instead.
func (*ListQuoteLinesRequest) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{21}
}

func (x *ListQuoteLinesRequest) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *ListQuoteLinesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListQuoteLinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Lines         []*QuoteLine           `protobuf:"bytes,3,rep,name=lines,proto3" json:"lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQuoteLinesResponse) Reset() {
	*x = ListQuoteLinesResponse{}
	mi := &file_quote_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQuoteLinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQuoteLinesResponse) ProtoMessage() {}

func (x *ListQuoteLinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQuoteLinesResponse.ProtoReflect.Descriptor instead.
func (*ListQuoteLinesResponse) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{22}
}

func (x *ListQuoteLinesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListQuoteLinesResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListQuoteLinesResponse) GetLines() []*QuoteLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

type UpdateQuoteLineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LineId        string                 `protobuf:"bytes,1,opt,name=line_id,json=lineId,proto3" json:"line_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Quantity      string                 `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Unit          string                 `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	UnitPrice     int64                  `protobuf:"varint,7,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Data          string                 `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	Position      int32                  `protobuf:"varint,9,opt,name=position,proto3" json:"position,omitempty"`
	TaxId         int32                  `protobuf:"varint,10,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuoteLineRequest) Reset() {
	*x = UpdateQuoteLineRequest{}
	mi := &file_quote_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuoteLineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuoteLineRequest) ProtoMessage() {}

func (x *UpdateQuoteLineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuoteLineRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuoteLineRequest) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateQuoteLineRequest) GetLineId() string {
	if x != nil {
		return x.LineId
	}
	return ""
}

func (x *UpdateQuoteLineRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateQuoteLineRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateQuoteLineRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateQuoteLineRequest) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

func (x *UpdateQuoteLineRequest) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *UpdateQuoteLineRequest) GetUnitPrice() int64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *UpdateQuoteLineRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *UpdateQuoteLineRequest) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *UpdateQuoteLineRequest) GetTaxId() int32 {
	if x != nil {
		return x.TaxId
	}
	return 0
}

type UpdateQuoteLineResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuoteLineResponse) Reset() {
	*x = UpdateQuoteLineResponse{}
	mi := &file_quote_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuoteLineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuoteLineResponse) ProtoMessage() {}

func (x *UpdateQuoteLineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuoteLineResponse.ProtoReflect.Descriptor instead.
func (*UpdateQuoteLineResponse) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateQuoteLineResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateQuoteLineResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type DeleteQuoteLineRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LineId        string                 `protobuf:"bytes,1,opt,name=line_id,json=lineId,proto3" json:"line_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteQuoteLineRequest) Reset() {
	*x = DeleteQuoteLineRequest{}
	mi := &file_quote_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteQuoteLineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteQuoteLineRequest) ProtoMessage() {}

func (x *DeleteQuoteLineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quote_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteQuoteLineRequest.ProtoReflect.Descriptor instead.
func (*DeleteQuoteLineRequest) Descriptor() ([]byte, []int) {
	return file_quote_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteQuoteLineRequest) GetLineId() string {
	if x != nil {
		return x.LineId
	}
	return ""
}

func (x *DeleteQuoteLineRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_quote_proto protoreflect.FileDescriptor

const file_quote_proto_rawDesc = "" +
	"\n" +
	"\vquote.proto\x12\x05quote\"?\n" +
	"\x0fGenericResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"\xd0\x01\n" +
	"\x05Quote\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\barchived\x18\x04 \x01(\bR\barchived\x12'\n" +
	"\x05state\x18\x05 \x01(\x0e2\x11.quote.QuoteStateR\x05state\x12\x1b\n" +
	"\tclient_id\x18\x06 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"address_id\x18\a \x01(\x05R\taddressId\"}\n" +
	"\x12CreateQuoteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"address_id\x18\x04 \x01(\x05R\taddressId\"^\n" +
	"\x13CreateQuoteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x19\n" +
	"\bquote_id\x18\x03 \x01(\tR\aquoteId\"E\n" +
	"\x0fGetQuoteRequest\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x8c\x01\n" +
	"\x10GetQuoteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\"\n" +
	"\x05quote\x18\x03 \x01(\v2\f.quote.QuoteR\x05quote\x12&\n" +
	"\x05lines\x18\x04 \x03(\v2\x10.quote.QuoteLineR\x05lines\"W\n" +
	"\x11ListQuotesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12)\n" +
	"\x10include_archived\x18\x02 \x01(\bR\x0fincludeArchived\"h\n" +
	"\x12ListQuotesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12$\n" +
	"\x06quotes\x18\x03 \x03(\v2\f.quote.QuoteR\x06quotes\"\x98\x01\n" +
	"\x12UpdateQuoteRequest\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"address_id\x18\x05 \x01(\x05R\taddressId\"C\n" +
	"\x13UpdateQuoteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"H\n" +
	"\x12DeleteQuoteRequest\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"I\n" +
	"\x13ArchiveQuoteRequest\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"I\n" +
	"\x13RestoreQuoteRequest\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"-\n" +
	"\x12TrashQuotesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"F\n" +
	"\x10DropQuoteRequest\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"J\n" +
	"\x14ContinueQuoteRequest\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xfd\x01\n" +
	"\tQuoteLine\x12\x17\n" +
	"\aline_id\x18\x01 \x01(\tR\x06lineId\x12\x19\n" +
	"\bquote_id\x18\x02 \x01(\tR\aquoteId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\tR\bquantity\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unit\x12\x1d\n" +
	"\n" +
	"unit_price\x18\a \x01(\x03R\tunitPrice\x12\x12\n" +
	"\x04data\x18\b \x01(\tR\x04data\x12\x1a\n" +
	"\bposition\x18\t \x01(\x05R\bposition\x12\x15\n" +
	"\x06tax_id\x18\n" +
	" \x01(\x05R\x05taxId\"\x8a\x02\n" +
	"\x16CreateQuoteLineRequest\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\tR\bquantity\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unit\x12\x1d\n" +
	"\n" +
	"unit_price\x18\a \x01(\x03R\tunitPrice\x12\x12\n" +
	"\x04data\x18\b \x01(\tR\x04data\x12\x1a\n" +
	"\bposition\x18\t \x01(\x05R\bposition\x12\x15\n" +
	"\x06tax_id\x18\n" +
	" \x01(\x05R\x05taxId\"`\n" +
	"\x17CreateQuoteLineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x17\n" +
	"\aline_id\x18\x03 \x01(\tR\x06lineId\"G\n" +
	"\x13GetQuoteLineRequest\x12\x17\n" +
	"\aline_id\x18\x01 \x01(\tR\x06lineId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"j\n" +
	"\x14GetQuoteLineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12$\n" +
	"\x04line\x18\x03 \x01(\v2\x10.quote.QuoteLineR\x04line\"K\n" +
	"\x15ListQuoteLinesRequest\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"n\n" +
	"\x16ListQuoteLinesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12&\n" +
	"\x05lines\x18\x03 \x03(\v2\x10.quote.QuoteLineR\x05lines\"\x88\x02\n" +
	"\x16UpdateQuoteLineRequest\x12\x17\n" +
	"\aline_id\x18\x01 \x01(\tR\x06lineId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\tR\bquantity\x12\x12\n" +
	"\x04unit\x18\x06 \x01(\tR\x04unit\x12\x1d\n" +
	"\n" +
	"unit_price\x18\a \x01(\x03R\tunitPrice\x12\x12\n" +
	"\x04data\x18\b \x01(\tR\x04data\x12\x1a\n" +
	"\bposition\x18\t \x01(\x05R\bposition\x12\x15\n" +
	"\x06tax_id\x18\n" +
	" \x01(\x05R\x05taxId\"G\n" +
	"\x17UpdateQuoteLineResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"J\n" +
	"\x16DeleteQuoteLineRequest\x12\x17\n" +
	"\aline_id\x18\x01 \x01(\tR\x06lineId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId*\x87\x01\n" +
	"\n" +
	"QuoteState\x12\x1b\n" +
	"\x17QUOTE_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11QUOTE_STATE_DRAFT\x10\x01\x12\x14\n" +
	"\x10QUOTE_STATE_SENT\x10\x02\x12\x19\n" +
	"\x15QUOTE_STATE_VALIDATED\x10\x03\x12\x14\n" +
	"\x10QUOTE_STATE_DROP\x10\x042\xb0\b\n" +
	"\fQuoteService\x12D\n" +
	"\vCreateQuote\x12\x19.quote.CreateQuoteRequest\x1a\x1a.quote.CreateQuoteResponse\x12;\n" +
	"\bGetQuote\x12\x16.quote.GetQuoteRequest\x1a\x17.quote.GetQuoteResponse\x12A\n" +
	"\n" +
	"ListQuotes\x12\x18.quote.ListQuotesRequest\x1a\x19.quote.ListQuotesResponse\x12D\n" +
	"\vUpdateQuote\x12\x19.quote.UpdateQuoteRequest\x1a\x1a.quote.UpdateQuoteResponse\x12@\n" +
	"\vDeleteQuote\x12\x19.quote.DeleteQuoteRequest\x1a\x16.quote.GenericResponse\x12B\n" +
	"\fArchiveQuote\x12\x1a.quote.ArchiveQuoteRequest\x1a\x16.quote.GenericResponse\x12B\n" +
	"\fRestoreQuote\x12\x1a.quote.RestoreQuoteRequest\x1a\x16.quote.GenericResponse\x12@\n" +
	"\vTrashQuotes\x12\x19.quote.TrashQuotesRequest\x1a\x16.quote.GenericResponse\x12<\n" +
	"\tDropQuote\x12\x17.quote.DropQuoteRequest\x1a\x16.quote.GenericResponse\x12D\n" +
	"\rContinueQuote\x12\x1b.quote.ContinueQuoteRequest\x1a\x16.quote.GenericResponse\x12P\n" +
	"\x0fCreateQuoteLine\x12\x1d.quote.CreateQuoteLineRequest\x1a\x1e.quote.CreateQuoteLineResponse\x12G\n" +
	"\fGetQuoteLine\x12\x1a.quote.GetQuoteLineRequest\x1a\x1b.quote.GetQuoteLineResponse\x12M\n" +
	"\x0eListQuoteLines\x12\x1c.quote.ListQuoteLinesRequest\x1a\x1d.quote.ListQuoteLinesResponse\x12P\n" +
	"\x0fUpdateQuoteLine\x12\x1d.quote.UpdateQuoteLineRequest\x1a\x1e.quote.UpdateQuoteLineResponse\x12H\n" +
	"\x0fDeleteQuoteLine\x12\x1d.quote.DeleteQuoteLineRequest\x1a\x16.quote.GenericResponseB\x1cZ\x1aproject-devis-export/quoteb\x06proto3"

var (
	file_quote_proto_rawDescOnce sync.Once
	file_quote_proto_rawDescData []byte
)

func file_quote_proto_rawDescGZIP() []byte {
	file_quote_proto_rawDescOnce.Do(func() {
		file_quote_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quote_proto_rawDesc), len(file_quote_proto_rawDesc)))
	})
	return file_quote_proto_rawDescData
}

var file_quote_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_quote_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_quote_proto_goTypes = []any{
	(QuoteState)(0),                 // 0: quote.QuoteState
	(*GenericResponse)(nil),         // 1: quote.GenericResponse
	(*Quote)(nil),                   // 2: quote.Quote
	(*CreateQuoteRequest)(nil),      // 3: quote.CreateQuoteRequest
	(*CreateQuoteResponse)(nil),     // 4: quote.CreateQuoteResponse
	(*GetQuoteRequest)(nil),         // 5: quote.GetQuoteRequest
	(*GetQuoteResponse)(nil),        // 6: quote.GetQuoteResponse
	(*ListQuotesRequest)(nil),       // 7: quote.ListQuotesRequest
	(*ListQuotesResponse)(nil),      // 8: quote.ListQuotesResponse
	(*UpdateQuoteRequest)(nil),      // 9: quote.UpdateQuoteRequest
	(*UpdateQuoteResponse)(nil),     // 10: quote.UpdateQuoteResponse
	(*DeleteQuoteRequest)(nil),      // 11: quote.DeleteQuoteRequest
	(*ArchiveQuoteRequest)(nil),     // 12: quote.ArchiveQuoteRequest
	(*RestoreQuoteRequest)(nil),     // 13: quote.RestoreQuoteRequest
	(*TrashQuotesRequest)(nil),      // 14: quote.TrashQuotesRequest
	(*DropQuoteRequest)(nil),        // 15: quote.DropQuoteRequest
	(*ContinueQuoteRequest)(nil),    // 16: quote.ContinueQuoteRequest
	(*QuoteLine)(nil),               // 17: quote.QuoteLine
	(*CreateQuoteLineRequest)(nil),  // 18: quote.CreateQuoteLineRequest
	(*CreateQuoteLineResponse)(nil), // 19: quote.CreateQuoteLineResponse
	(*GetQuoteLineRequest)(nil),     // 20: quote.GetQuoteLineRequest
	(*GetQuoteLineResponse)(nil),    // 21: quote.GetQuoteLineResponse
	(*ListQuoteLinesRequest)(nil),   // 22: quote.ListQuoteLinesRequest
	(*ListQuoteLinesResponse)(nil),  // 23: quote.ListQuoteLinesResponse
	(*UpdateQuoteLineRequest)(nil),  // 24: quote.UpdateQuoteLineRequest
	(*UpdateQuoteLineResponse)(nil), // 25: quote.UpdateQuoteLineResponse
	(*DeleteQuoteLineRequest)(nil),  // 26: quote.DeleteQuoteLineRequest
}
var file_quote_proto_depIdxs = []int32{
	0,  // 0: quote.Quote.state:type_name -> quote.QuoteState
	2,  // 1: quote.GetQuoteResponse.quote:type_name -> quote.Quote
	17, // 2: quote.GetQuoteResponse.lines:type_name -> quote.QuoteLine
	2,  // 3: quote.ListQuotesResponse.quotes:type_name -> quote.Quote
	17, // 4: quote.GetQuoteLineResponse.line:type_name -> quote.QuoteLine
	17, // 5: quote.ListQuoteLinesResponse.lines:type_name -> quote.QuoteLine
	3,  // 6: quote.QuoteService.CreateQuote:input_type -> quote.CreateQuoteRequest
	5,  // 7: quote.QuoteService.GetQuote:input_type -> quote.GetQuoteRequest
	7,  // 8: quote.QuoteService.ListQuotes:input_type -> quote.ListQuotesRequest
	9,  // 9: quote.QuoteService.UpdateQuote:input_type -> quote.UpdateQuoteRequest
	11, // 10: quote.QuoteService.DeleteQuote:input_type -> quote.DeleteQuoteRequest
	12, // 11: quote.QuoteService.ArchiveQuote:input_type -> quote.ArchiveQuoteRequest
	13, // 12: quote.QuoteService.RestoreQuote:input_type -> quote.RestoreQuoteRequest
	14, // 13: quote.QuoteService.TrashQuotes:input_type -> quote.TrashQuotesRequest
	15, // 14: quote.QuoteService.DropQuote:input_type -> quote.DropQuoteRequest
	16, // 15: quote.QuoteService.ContinueQuote:input_type -> quote.ContinueQuoteRequest
	18, // 16: quote.QuoteService.CreateQuoteLine:input_type -> quote.CreateQuoteLineRequest
	20, // 17: quote.QuoteService.GetQuoteLine:input_type -> quote.GetQuoteLineRequest
	22, // 18: quote.QuoteService.ListQuoteLines:input_type -> quote.ListQuoteLinesRequest
	24, // 19: quote.QuoteService.UpdateQuoteLine:input_type -> quote.UpdateQuoteLineRequest
	26, // 20: quote.QuoteService.DeleteQuoteLine:input_type -> quote.DeleteQuoteLineRequest
	4,  // 21: quote.QuoteService.CreateQuote:output_type -> quote.CreateQuoteResponse
	6,  // 22: quote.QuoteService.GetQuote:output_type -> quote.GetQuoteResponse
	8,  // 23: quote.QuoteService.ListQuotes:output_type -> quote.ListQuotesResponse
	10, // 24: quote.QuoteService.UpdateQuote:output_type -> quote.UpdateQuoteResponse
	1,  // 25: quote.QuoteService.DeleteQuote:output_type -> quote.GenericResponse
	1,  // 26: quote.QuoteService.ArchiveQuote:output_type -> quote.GenericResponse
	1,  // 27: quote.QuoteService.RestoreQuote:output_type -> quote.GenericResponse
	1,  // 28: quote.QuoteService.TrashQuotes:output_type -> quote.GenericResponse
	1,  // 29: quote.QuoteService.DropQuote:output_type -> quote.GenericResponse
	1,  // 30: quote.QuoteService.ContinueQuote:output_type -> quote.GenericResponse
	19, // 31: quote.QuoteService.CreateQuoteLine:output_type -> quote.CreateQuoteLineResponse
	21, // 32: quote.QuoteService.GetQuoteLine:output_type -> quote.GetQuoteLineResponse
	23, // 33: quote.QuoteService.ListQuoteLines:output_type -> quote.ListQuoteLinesResponse
	25, // 34: quote.QuoteService.UpdateQuoteLine:output_type -> quote.UpdateQuoteLineResponse
	1,  // 35: quote.QuoteService.DeleteQuoteLine:output_type -> quote.GenericResponse
	21, // [21:36] is the sub-list for method output_type
	6,  // [6:21] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_quote_proto_init() }
func file_quote_proto_init() {
	if File_quote_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quote_proto_rawDesc), len(file_quote_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quote_proto_goTypes,
		DependencyIndexes: file_quote_proto_depIdxs,
		EnumInfos:         file_quote_proto_enumTypes,
		MessageInfos:      file_quote_proto_msgTypes,
	}.Build()
	File_quote_proto = out.File
	file_quote_proto_goTypes = nil
	file_quote_proto_depIdxs = nil
}
