// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: quote.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuoteService_CreateQuote_FullMethodName        = "/quote.QuoteService/CreateQuote"
	QuoteService_GetQuote_FullMethodName           = "/quote.QuoteService/GetQuote"
	QuoteService_ListQuotes_FullMethodName         = "/quote.QuoteService/ListQuotes"
	QuoteService_UpdateQuote_FullMethodName        = "/quote.QuoteService/UpdateQuote"
	QuoteService_DeleteQuote_FullMethodName        = "/quote.QuoteService/DeleteQuote"
	QuoteService_ArchiveQuote_FullMethodName       = "/quote.QuoteService/ArchiveQuote"
	QuoteService_RestoreQuote_FullMethodName       = "/quote.QuoteService/RestoreQuote"
	QuoteService_TrashQuotes_FullMethodName        = "/quote.QuoteService/TrashQuotes"
	QuoteService_DropQuote_FullMethodName          = "/quote.QuoteService/DropQuote"
	QuoteService_ContinueQuote_FullMethodName      = "/quote.QuoteService/ContinueQuote"
	QuoteService_ValidateQuote_FullMethodName      = "/quote.QuoteService/ValidateQuote"
	QuoteService_NegociateQuote_FullMethodName     = "/quote.QuoteService/NegociateQuote"
	QuoteService_CreateQuoteLine_FullMethodName    = "/quote.QuoteService/CreateQuoteLine"
	QuoteService_GetQuoteLine_FullMethodName       = "/quote.QuoteService/GetQuoteLine"
	QuoteService_ListQuoteLines_FullMethodName     = "/quote.QuoteService/ListQuoteLines"
	QuoteService_ListUserQuoteLines_FullMethodName = "/quote.QuoteService/ListUserQuoteLines"
	QuoteService_UpdateQuoteLine_FullMethodName    = "/quote.QuoteService/UpdateQuoteLine"
	QuoteService_DeleteQuoteLine_FullMethodName    = "/quote.QuoteService/DeleteQuoteLine"
	QuoteService_CreateFee_FullMethodName          = "/quote.QuoteService/CreateFee"
	QuoteService_GetFee_FullMethodName             = "/quote.QuoteService/GetFee"
	QuoteService_ListFees_FullMethodName           = "/quote.QuoteService/ListFees"
	QuoteService_UpdateFee_FullMethodName          = "/quote.QuoteService/UpdateFee"
	QuoteService_ArchiveFee_FullMethodName         = "/quote.QuoteService/ArchiveFee"
	QuoteService_CreateComment_FullMethodName      = "/quote.QuoteService/CreateComment"
	QuoteService_ListComments_FullMethodName       = "/quote.QuoteService/ListComments"
	QuoteService_UpdateComment_FullMethodName      = "/quote.QuoteService/UpdateComment"
	QuoteService_DeleteComment_FullMethodName      = "/quote.QuoteService/DeleteComment"
)

// QuoteServiceClient is the client API for QuoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuoteServiceClient interface {
	// Quote
	CreateQuote(ctx context.Context, in *CreateQuoteRequest, opts ...grpc.CallOption) (*CreateQuoteResponse, error)
	GetQuote(ctx context.Context, in *GetQuoteRequest, opts ...grpc.CallOption) (*GetQuoteResponse, error)
	ListQuotes(ctx context.Context, in *ListQuotesRequest, opts ...grpc.CallOption) (*ListQuotesResponse, error)
	UpdateQuote(ctx context.Context, in *UpdateQuoteRequest, opts ...grpc.CallOption) (*UpdateQuoteResponse, error)
	DeleteQuote(ctx context.Context, in *DeleteQuoteRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	ArchiveQuote(ctx context.Context, in *ArchiveQuoteRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	RestoreQuote(ctx context.Context, in *RestoreQuoteRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	TrashQuotes(ctx context.Context, in *TrashQuotesRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	DropQuote(ctx context.Context, in *DropQuoteRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	ContinueQuote(ctx context.Context, in *ContinueQuoteRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	ValidateQuote(ctx context.Context, in *ValidateQuoteRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	NegociateQuote(ctx context.Context, in *NegociateQuoteRequest, opts ...grpc.CallOption) (*NegociateQuoteResponse, error)
	// Line
	CreateQuoteLine(ctx context.Context, in *CreateQuoteLineRequest, opts ...grpc.CallOption) (*CreateQuoteLineResponse, error)
	GetQuoteLine(ctx context.Context, in *GetQuoteLineRequest, opts ...grpc.CallOption) (*GetQuoteLineResponse, error)
	ListQuoteLines(ctx context.Context, in *ListQuoteLinesRequest, opts ...grpc.CallOption) (*ListQuoteLinesResponse, error)
	ListUserQuoteLines(ctx context.Context, in *ListUserQuoteLinesRequest, opts ...grpc.CallOption) (*ListUserQuoteLinesResponse, error)
	UpdateQuoteLine(ctx context.Context, in *UpdateQuoteLineRequest, opts ...grpc.CallOption) (*UpdateQuoteLineResponse, error)
	DeleteQuoteLine(ctx context.Context, in *DeleteQuoteLineRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	// Fee (premium catalog)
	CreateFee(ctx context.Context, in *CreateFeeRequest, opts ...grpc.CallOption) (*CreateFeeResponse, error)
	GetFee(ctx context.Context, in *GetFeeRequest, opts ...grpc.CallOption) (*GetFeeResponse, error)
	ListFees(ctx context.Context, in *ListFeesRequest, opts ...grpc.CallOption) (*ListFeesResponse, error)
	UpdateFee(ctx context.Context, in *UpdateFeeRequest, opts ...grpc.CallOption) (*UpdateFeeResponse, error)
	ArchiveFee(ctx context.Context, in *ArchiveFeeRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	// Comment
	CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error)
	ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error)
	UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*UpdateCommentResponse, error)
	DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*GenericResponse, error)
}

type quoteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuoteServiceClient(cc grpc.ClientConnInterface) QuoteServiceClient {
	return &quoteServiceClient{cc}
}

func (c *quoteServiceClient) CreateQuote(ctx context.Context, in *CreateQuoteRequest, opts ...grpc.CallOption) (*CreateQuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateQuoteResponse)
	err := c.cc.Invoke(ctx, QuoteService_CreateQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) GetQuote(ctx context.Context, in *GetQuoteRequest, opts ...grpc.CallOption) (*GetQuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuoteResponse)
	err := c.cc.Invoke(ctx, QuoteService_GetQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) ListQuotes(ctx context.Context, in *ListQuotesRequest, opts ...grpc.CallOption) (*ListQuotesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListQuotesResponse)
	err := c.cc.Invoke(ctx, QuoteService_ListQuotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) UpdateQuote(ctx context.Context, in *UpdateQuoteRequest, opts ...grpc.CallOption) (*UpdateQuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateQuoteResponse)
	err := c.cc.Invoke(ctx, QuoteService_UpdateQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) DeleteQuote(ctx context.Context, in *DeleteQuoteRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, QuoteService_DeleteQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) ArchiveQuote(ctx context.Context, in *ArchiveQuoteRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, QuoteService_ArchiveQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) RestoreQuote(ctx context.Context, in *RestoreQuoteRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, QuoteService_RestoreQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) TrashQuotes(ctx context.Context, in *TrashQuotesRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, QuoteService_TrashQuotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) DropQuote(ctx context.Context, in *DropQuoteRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, QuoteService_DropQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) ContinueQuote(ctx context.Context, in *ContinueQuoteRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, QuoteService_ContinueQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) ValidateQuote(ctx context.Context, in *ValidateQuoteRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, QuoteService_ValidateQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) NegociateQuote(ctx context.Context, in *NegociateQuoteRequest, opts ...grpc.CallOption) (*NegociateQuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NegociateQuoteResponse)
	err := c.cc.Invoke(ctx, QuoteService_NegociateQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) CreateQuoteLine(ctx context.Context, in *CreateQuoteLineRequest, opts ...grpc.CallOption) (*CreateQuoteLineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateQuoteLineResponse)
	err := c.cc.Invoke(ctx, QuoteService_CreateQuoteLine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) GetQuoteLine(ctx context.Context, in *GetQuoteLineRequest, opts ...grpc.CallOption) (*GetQuoteLineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQuoteLineResponse)
	err := c.cc.Invoke(ctx, QuoteService_GetQuoteLine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) ListQuoteLines(ctx context.Context, in *ListQuoteLinesRequest, opts ...grpc.CallOption) (*ListQuoteLinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListQuoteLinesResponse)
	err := c.cc.Invoke(ctx, QuoteService_ListQuoteLines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) ListUserQuoteLines(ctx context.Context, in *ListUserQuoteLinesRequest, opts ...grpc.CallOption) (*ListUserQuoteLinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserQuoteLinesResponse)
	err := c.cc.Invoke(ctx, QuoteService_ListUserQuoteLines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) UpdateQuoteLine(ctx context.Context, in *UpdateQuoteLineRequest, opts ...grpc.CallOption) (*UpdateQuoteLineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateQuoteLineResponse)
	err := c.cc.Invoke(ctx, QuoteService_UpdateQuoteLine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) DeleteQuoteLine(ctx context.Context, in *DeleteQuoteLineRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, QuoteService_DeleteQuoteLine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) CreateFee(ctx context.Context, in *CreateFeeRequest, opts ...grpc.CallOption) (*CreateFeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFeeResponse)
	err := c.cc.Invoke(ctx, QuoteService_CreateFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) GetFee(ctx context.Context, in *GetFeeRequest, opts ...grpc.CallOption) (*GetFeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFeeResponse)
	err := c.cc.Invoke(ctx, QuoteService_GetFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) ListFees(ctx context.Context, in *ListFeesRequest, opts ...grpc.CallOption) (*ListFeesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFeesResponse)
	err := c.cc.Invoke(ctx, QuoteService_ListFees_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) UpdateFee(ctx context.Context, in *UpdateFeeRequest, opts ...grpc.CallOption) (*UpdateFeeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFeeResponse)
	err := c.cc.Invoke(ctx, QuoteService_UpdateFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) ArchiveFee(ctx context.Context, in *ArchiveFeeRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, QuoteService_ArchiveFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) CreateComment(ctx context.Context, in *CreateCommentRequest, opts ...grpc.CallOption) (*CreateCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCommentResponse)
	err := c.cc.Invoke(ctx, QuoteService_CreateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) ListComments(ctx context.Context, in *ListCommentsRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommentsResponse)
	err := c.cc.Invoke(ctx, QuoteService_ListComments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) UpdateComment(ctx context.Context, in *UpdateCommentRequest, opts ...grpc.CallOption) (*UpdateCommentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCommentResponse)
	err := c.cc.Invoke(ctx, QuoteService_UpdateComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteServiceClient) DeleteComment(ctx context.Context, in *DeleteCommentRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, QuoteService_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuoteServiceServer is the server API for QuoteService service.
// All implementations must embed UnimplementedQuoteServiceServer
// for forward compatibility.
type QuoteServiceServer interface {
	// Quote
	CreateQuote(context.Context, *CreateQuoteRequest) (*CreateQuoteResponse, error)
	GetQuote(context.Context, *GetQuoteRequest) (*GetQuoteResponse, error)
	ListQuotes(context.Context, *ListQuotesRequest) (*ListQuotesResponse, error)
	UpdateQuote(context.Context, *UpdateQuoteRequest) (*UpdateQuoteResponse, error)
	DeleteQuote(context.Context, *DeleteQuoteRequest) (*GenericResponse, error)
	ArchiveQuote(context.Context, *ArchiveQuoteRequest) (*GenericResponse, error)
	RestoreQuote(context.Context, *RestoreQuoteRequest) (*GenericResponse, error)
	TrashQuotes(context.Context, *TrashQuotesRequest) (*GenericResponse, error)
	DropQuote(context.Context, *DropQuoteRequest) (*GenericResponse, error)
	ContinueQuote(context.Context, *ContinueQuoteRequest) (*GenericResponse, error)
	ValidateQuote(context.Context, *ValidateQuoteRequest) (*GenericResponse, error)
	NegociateQuote(context.Context, *NegociateQuoteRequest) (*NegociateQuoteResponse, error)
	// Line
	CreateQuoteLine(context.Context, *CreateQuoteLineRequest) (*CreateQuoteLineResponse, error)
	GetQuoteLine(context.Context, *GetQuoteLineRequest) (*GetQuoteLineResponse, error)
	ListQuoteLines(context.Context, *ListQuoteLinesRequest) (*ListQuoteLinesResponse, error)
	ListUserQuoteLines(context.Context, *ListUserQuoteLinesRequest) (*ListUserQuoteLinesResponse, error)
	UpdateQuoteLine(context.Context, *UpdateQuoteLineRequest) (*UpdateQuoteLineResponse, error)
	DeleteQuoteLine(context.Context, *DeleteQuoteLineRequest) (*GenericResponse, error)
	// Fee (premium catalog)
	CreateFee(context.Context, *CreateFeeRequest) (*CreateFeeResponse, error)
	GetFee(context.Context, *GetFeeRequest) (*GetFeeResponse, error)
	ListFees(context.Context, *ListFeesRequest) (*ListFeesResponse, error)
	UpdateFee(context.Context, *UpdateFeeRequest) (*UpdateFeeResponse, error)
	ArchiveFee(context.Context, *ArchiveFeeRequest) (*GenericResponse, error)
	// Comment
	CreateComment(context.Context, *CreateCommentRequest) (*CreateCommentResponse, error)
	ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error)
	UpdateComment(context.Context, *UpdateCommentRequest) (*UpdateCommentResponse, error)
	DeleteComment(context.Context, *DeleteCommentRequest) (*GenericResponse, error)
	mustEmbedUnimplementedQuoteServiceServer()
}

// UnimplementedQuoteServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuoteServiceServer struct{}

func (UnimplementedQuoteServiceServer) CreateQuote(context.Context, *CreateQuoteRequest) (*CreateQuoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateQuote not implemented")
}
func (UnimplementedQuoteServiceServer) GetQuote(context.Context, *GetQuoteRequest) (*GetQuoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQuote not implemented")
}
func (UnimplementedQuoteServiceServer) ListQuotes(context.Context, *ListQuotesRequest) (*ListQuotesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListQuotes not implemented")
}
func (UnimplementedQuoteServiceServer) UpdateQuote(context.Context, *UpdateQuoteRequest) (*UpdateQuoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateQuote not implemented")
}
func (UnimplementedQuoteServiceServer) DeleteQuote(context.Context, *DeleteQuoteRequest) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteQuote not implemented")
}
func (UnimplementedQuoteServiceServer) ArchiveQuote(context.Context, *ArchiveQuoteRequest) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchiveQuote not implemented")
}
func (UnimplementedQuoteServiceServer) RestoreQuote(context.Context, *RestoreQuoteRequest) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreQuote not implemented")
}
func (UnimplementedQuoteServiceServer) TrashQuotes(context.Context, *TrashQuotesRequest) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TrashQuotes not implemented")
}
func (UnimplementedQuoteServiceServer) DropQuote(context.Context, *DropQuoteRequest) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DropQuote not implemented")
}
func (UnimplementedQuoteServiceServer) ContinueQuote(context.Context, *ContinueQuoteRequest) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ContinueQuote not implemented")
}
func (UnimplementedQuoteServiceServer) ValidateQuote(context.Context, *ValidateQuoteRequest) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateQuote not implemented")
}
func (UnimplementedQuoteServiceServer) NegociateQuote(context.Context, *NegociateQuoteRequest) (*NegociateQuoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NegociateQuote not implemented")
}
func (UnimplementedQuoteServiceServer) CreateQuoteLine(context.Context, *CreateQuoteLineRequest) (*CreateQuoteLineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateQuoteLine not implemented")
}
func (UnimplementedQuoteServiceServer) GetQuoteLine(context.Context, *GetQuoteLineRequest) (*GetQuoteLineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQuoteLine not implemented")
}
func (UnimplementedQuoteServiceServer) ListQuoteLines(context.Context, *ListQuoteLinesRequest) (*ListQuoteLinesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListQuoteLines not implemented")
}
func (UnimplementedQuoteServiceServer) ListUserQuoteLines(context.Context, *ListUserQuoteLinesRequest) (*ListUserQuoteLinesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserQuoteLines not implemented")
}
func (UnimplementedQuoteServiceServer) UpdateQuoteLine(context.Context, *UpdateQuoteLineRequest) (*UpdateQuoteLineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateQuoteLine not implemented")
}
func (UnimplementedQuoteServiceServer) DeleteQuoteLine(context.Context, *DeleteQuoteLineRequest) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteQuoteLine not implemented")
}
func (UnimplementedQuoteServiceServer) CreateFee(context.Context, *CreateFeeRequest) (*CreateFeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFee not implemented")
}
func (UnimplementedQuoteServiceServer) GetFee(context.Context, *GetFeeRequest) (*GetFeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFee not implemented")
}
func (UnimplementedQuoteServiceServer) ListFees(context.Context, *ListFeesRequest) (*ListFeesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFees not implemented")
}
func (UnimplementedQuoteServiceServer) UpdateFee(context.Context, *UpdateFeeRequest) (*UpdateFeeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFee not implemented")
}
func (UnimplementedQuoteServiceServer) ArchiveFee(context.Context, *ArchiveFeeRequest) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchiveFee not implemented")
}
func (UnimplementedQuoteServiceServer) CreateComment(context.Context, *CreateCommentRequest) (*CreateCommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedQuoteServiceServer) ListComments(context.Context, *ListCommentsRequest) (*ListCommentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListComments not implemented")
}
func (UnimplementedQuoteServiceServer) UpdateComment(context.Context, *UpdateCommentRequest) (*UpdateCommentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateComment not implemented")
}
func (UnimplementedQuoteServiceServer) DeleteComment(context.Context, *DeleteCommentRequest) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedQuoteServiceServer) mustEmbedUnimplementedQuoteServiceServer() {}
func (UnimplementedQuoteServiceServer) testEmbeddedByValue()                      {}

// UnsafeQuoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuoteServiceServer will
// result in compilation errors.
type UnsafeQuoteServiceServer interface {
	mustEmbedUnimplementedQuoteServiceServer()
}

func RegisterQuoteServiceServer(s grpc.ServiceRegistrar, srv QuoteServiceServer) {
	// If the following call panics, it indicates UnimplementedQuoteServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuoteService_ServiceDesc, srv)
}

func _QuoteService_CreateQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).CreateQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_CreateQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).CreateQuote(ctx, req.(*CreateQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_GetQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).GetQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_GetQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).GetQuote(ctx, req.(*GetQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_ListQuotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQuotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).ListQuotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_ListQuotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).ListQuotes(ctx, req.(*ListQuotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_UpdateQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).UpdateQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_UpdateQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).UpdateQuote(ctx, req.(*UpdateQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_DeleteQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).DeleteQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_DeleteQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).DeleteQuote(ctx, req.(*DeleteQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_ArchiveQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).ArchiveQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_ArchiveQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).ArchiveQuote(ctx, req.(*ArchiveQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_RestoreQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).RestoreQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_RestoreQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).RestoreQuote(ctx, req.(*RestoreQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_TrashQuotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TrashQuotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).TrashQuotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_TrashQuotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).TrashQuotes(ctx, req.(*TrashQuotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_DropQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).DropQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_DropQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).DropQuote(ctx, req.(*DropQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_ContinueQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContinueQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).ContinueQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_ContinueQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).ContinueQuote(ctx, req.(*ContinueQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_ValidateQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).ValidateQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_ValidateQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).ValidateQuote(ctx, req.(*ValidateQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_NegociateQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NegociateQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).NegociateQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_NegociateQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).NegociateQuote(ctx, req.(*NegociateQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_CreateQuoteLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQuoteLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).CreateQuoteLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_CreateQuoteLine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).CreateQuoteLine(ctx, req.(*CreateQuoteLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_GetQuoteLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuoteLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).GetQuoteLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_GetQuoteLine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).GetQuoteLine(ctx, req.(*GetQuoteLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_ListQuoteLines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQuoteLinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).ListQuoteLines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_ListQuoteLines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).ListQuoteLines(ctx, req.(*ListQuoteLinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_ListUserQuoteLines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserQuoteLinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).ListUserQuoteLines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_ListUserQuoteLines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).ListUserQuoteLines(ctx, req.(*ListUserQuoteLinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_UpdateQuoteLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateQuoteLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).UpdateQuoteLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_UpdateQuoteLine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).UpdateQuoteLine(ctx, req.(*UpdateQuoteLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_DeleteQuoteLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteQuoteLineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).DeleteQuoteLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_DeleteQuoteLine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).DeleteQuoteLine(ctx, req.(*DeleteQuoteLineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_CreateFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).CreateFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_CreateFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).CreateFee(ctx, req.(*CreateFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_GetFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).GetFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_GetFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).GetFee(ctx, req.(*GetFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_ListFees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFeesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).ListFees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_ListFees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).ListFees(ctx, req.(*ListFeesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_UpdateFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).UpdateFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_UpdateFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).UpdateFee(ctx, req.(*UpdateFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_ArchiveFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).ArchiveFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_ArchiveFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).ArchiveFee(ctx, req.(*ArchiveFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).CreateComment(ctx, req.(*CreateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_ListComments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).ListComments(ctx, req.(*ListCommentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_UpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).UpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_UpdateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).UpdateComment(ctx, req.(*UpdateCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteService_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteServiceServer).DeleteComment(ctx, req.(*DeleteCommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuoteService_ServiceDesc is the grpc.ServiceDesc for QuoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quote.QuoteService",
	HandlerType: (*QuoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateQuote",
			Handler:    _QuoteService_CreateQuote_Handler,
		},
		{
			MethodName: "GetQuote",
			Handler:    _QuoteService_GetQuote_Handler,
		},
		{
			MethodName: "ListQuotes",
			Handler:    _QuoteService_ListQuotes_Handler,
		},
		{
			MethodName: "UpdateQuote",
			Handler:    _QuoteService_UpdateQuote_Handler,
		},
		{
			MethodName: "DeleteQuote",
			Handler:    _QuoteService_DeleteQuote_Handler,
		},
		{
			MethodName: "ArchiveQuote",
			Handler:    _QuoteService_ArchiveQuote_Handler,
		},
		{
			MethodName: "RestoreQuote",
			Handler:    _QuoteService_RestoreQuote_Handler,
		},
		{
			MethodName: "TrashQuotes",
			Handler:    _QuoteService_TrashQuotes_Handler,
		},
		{
			MethodName: "DropQuote",
			Handler:    _QuoteService_DropQuote_Handler,
		},
		{
			MethodName: "ContinueQuote",
			Handler:    _QuoteService_ContinueQuote_Handler,
		},
		{
			MethodName: "ValidateQuote",
			Handler:    _QuoteService_ValidateQuote_Handler,
		},
		{
			MethodName: "NegociateQuote",
			Handler:    _QuoteService_NegociateQuote_Handler,
		},
		{
			MethodName: "CreateQuoteLine",
			Handler:    _QuoteService_CreateQuoteLine_Handler,
		},
		{
			MethodName: "GetQuoteLine",
			Handler:    _QuoteService_GetQuoteLine_Handler,
		},
		{
			MethodName: "ListQuoteLines",
			Handler:    _QuoteService_ListQuoteLines_Handler,
		},
		{
			MethodName: "ListUserQuoteLines",
			Handler:    _QuoteService_ListUserQuoteLines_Handler,
		},
		{
			MethodName: "UpdateQuoteLine",
			Handler:    _QuoteService_UpdateQuoteLine_Handler,
		},
		{
			MethodName: "DeleteQuoteLine",
			Handler:    _QuoteService_DeleteQuoteLine_Handler,
		},
		{
			MethodName: "CreateFee",
			Handler:    _QuoteService_CreateFee_Handler,
		},
		{
			MethodName: "GetFee",
			Handler:    _QuoteService_GetFee_Handler,
		},
		{
			MethodName: "ListFees",
			Handler:    _QuoteService_ListFees_Handler,
		},
		{
			MethodName: "UpdateFee",
			Handler:    _QuoteService_UpdateFee_Handler,
		},
		{
			MethodName: "ArchiveFee",
			Handler:    _QuoteService_ArchiveFee_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _QuoteService_CreateComment_Handler,
		},
		{
			MethodName: "ListComments",
			Handler:    _QuoteService_ListComments_Handler,
		},
		{
			MethodName: "UpdateComment",
			Handler:    _QuoteService_UpdateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _QuoteService_DeleteComment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quote.proto",
}
