// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: subscription.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenericResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericResponse) Reset() {
	*x = GenericResponse{}
	mi := &file_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericResponse) ProtoMessage() {}

func (x *GenericResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericResponse.ProtoReflect.Descriptor instead.
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *GenericResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenericResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type Plan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        int32                  `protobuf:"varint,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tier          string                 `protobuf:"bytes,3,opt,name=tier,proto3" json:"tier,omitempty"`
	PriceCents    int32                  `protobuf:"varint,4,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	BillingCycle  string                 `protobuf:"bytes,5,opt,name=billing_cycle,json=billingCycle,proto3" json:"billing_cycle,omitempty"`
	Features      string                 `protobuf:"bytes,6,opt,name=features,proto3" json:"features,omitempty"`
	Active        bool                   `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
	StripePriceId   string                 `protobuf:"bytes,8,opt,name=stripe_price_id,json=stripePriceId,proto3" json:"stripe_price_id,omitempty"`
	StripeProductId string                 `protobuf:"bytes,9,opt,name=stripe_product_id,json=stripeProductId,proto3" json:"stripe_product_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Plan) Reset() {
	*x = Plan{}
	mi := &file_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plan) ProtoMessage() {}

func (x *Plan) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Plan.ProtoReflect.Descriptor instead.
func (*Plan) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *Plan) GetPlanId() int32 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

func (x *Plan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Plan) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *Plan) GetPriceCents() int32 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *Plan) GetBillingCycle() string {
	if x != nil {
		return x.BillingCycle
	}
	return ""
}

func (x *Plan) GetFeatures() string {
	if x != nil {
		return x.Features
	}
	return ""
}

func (x *Plan) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Plan) GetStripePriceId() string {
	if x != nil {
		return x.StripePriceId
	}
	return ""
}

func (x *Plan) GetStripeProductId() string {
	if x != nil {
		return x.StripeProductId
	}
	return ""
}

type Subscription struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId       string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	UserId               string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanId               int32                  `protobuf:"varint,3,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Tier                 string                 `protobuf:"bytes,4,opt,name=tier,proto3" json:"tier,omitempty"`
	Status               string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CurrentPeriodStart   string                 `protobuf:"bytes,6,opt,name=current_period_start,json=currentPeriodStart,proto3" json:"current_period_start,omitempty"`
	CurrentPeriodEnd     string                 `protobuf:"bytes,7,opt,name=current_period_end,json=currentPeriodEnd,proto3" json:"current_period_end,omitempty"`
	CreatedAt            string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CancelAtPeriodEnd    bool                   `protobuf:"varint,10,opt,name=cancel_at_period_end,json=cancelAtPeriodEnd,proto3" json:"cancel_at_period_end,omitempty"`
	StripeSubscriptionId string                 `protobuf:"bytes,11,opt,name=stripe_subscription_id,json=stripeSubscriptionId,proto3" json:"stripe_subscription_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *Subscription) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *Subscription) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Subscription) GetPlanId() int32 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

func (x *Subscription) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *Subscription) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Subscription) GetCurrentPeriodStart() string {
	if x != nil {
		return x.CurrentPeriodStart
	}
	return ""
}

func (x *Subscription) GetCurrentPeriodEnd() string {
	if x != nil {
		return x.CurrentPeriodEnd
	}
	return ""
}

func (x *Subscription) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Subscription) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Subscription) GetCancelAtPeriodEnd() bool {
	if x != nil {
		return x.CancelAtPeriodEnd
	}
	return false
}

func (x *Subscription) GetStripeSubscriptionId() string {
	if x != nil {
		return x.StripeSubscriptionId
	}
	return ""
}

type ListPlansRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeInactive bool                   `protobuf:"varint,1,opt,name=include_inactive,json=includeInactive,proto3" json:"include_inactive,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListPlansRequest) Reset() {
	*x = ListPlansRequest{}
	mi := &file_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansRequest) ProtoMessage() {}

func (x *ListPlansRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansRequest.ProtoReflect.Descriptor instead.
func (*ListPlansRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *ListPlansRequest) GetIncludeInactive() bool {
	if x != nil {
		return x.IncludeInactive
	}
	return false
}

type ListPlansResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Plans         []*Plan                `protobuf:"bytes,3,rep,name=plans,proto3" json:"plans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPlansResponse) Reset() {
	*x = ListPlansResponse{}
	mi := &file_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPlansResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPlansResponse) ProtoMessage() {}

func (x *ListPlansResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPlansResponse.ProtoReflect.Descriptor instead.
func (*ListPlansResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *ListPlansResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListPlansResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListPlansResponse) GetPlans() []*Plan {
	if x != nil {
		return x.Plans
	}
	return nil
}

type GetPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        int32                  `protobuf:"varint,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanRequest) Reset() {
	*x = GetPlanRequest{}
	mi := &file_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanRequest) ProtoMessage() {}

func (x *GetPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanRequest.ProtoReflect.Descriptor instead.
func (*GetPlanRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{5}
}

func (x *GetPlanRequest) GetPlanId() int32 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

type GetPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Plan          *Plan                  `protobuf:"bytes,3,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlanResponse) Reset() {
	*x = GetPlanResponse{}
	mi := &file_subscription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlanResponse) ProtoMessage() {}

func (x *GetPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlanResponse.ProtoReflect.Descriptor instead.
func (*GetPlanResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{6}
}

func (x *GetPlanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetPlanResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetPlanResponse) GetPlan() *Plan {
	if x != nil {
		return x.Plan
	}
	return nil
}

type GetUserSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSubscriptionRequest) Reset() {
	*x = GetUserSubscriptionRequest{}
	mi := &file_subscription_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSubscriptionRequest) ProtoMessage() {}

func (x *GetUserSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*GetUserSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Subscription  *Subscription          `protobuf:"bytes,3,opt,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSubscriptionResponse) Reset() {
	*x = GetUserSubscriptionResponse{}
	mi := &file_subscription_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSubscriptionResponse) ProtoMessage() {}

func (x *GetUserSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*GetUserSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserSubscriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetUserSubscriptionResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserSubscriptionResponse) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

type ListSubscriptionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsRequest) Reset() {
	*x = ListSubscriptionsRequest{}
	mi := &file_subscription_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsRequest) ProtoMessage() {}

func (x *ListSubscriptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsRequest.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{9}
}

func (x *ListSubscriptionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSubscriptionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListSubscriptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Subscriptions []*Subscription        `protobuf:"bytes,3,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSubscriptionsResponse) Reset() {
	*x = ListSubscriptionsResponse{}
	mi := &file_subscription_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSubscriptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSubscriptionsResponse) ProtoMessage() {}

func (x *ListSubscriptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSubscriptionsResponse.ProtoReflect.Descriptor instead.
func (*ListSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{10}
}

func (x *ListSubscriptionsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListSubscriptionsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListSubscriptionsResponse) GetSubscriptions() []*Subscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *ListSubscriptionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AssignPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanId        int32                  `protobuf:"varint,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPlanRequest) Reset() {
	*x = AssignPlanRequest{}
	mi := &file_subscription_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPlanRequest) ProtoMessage() {}

func (x *AssignPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPlanRequest.ProtoReflect.Descriptor instead.
func (*AssignPlanRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{11}
}

func (x *AssignPlanRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AssignPlanRequest) GetPlanId() int32 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

type AssignPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	NewTier       string                 `protobuf:"bytes,3,opt,name=new_tier,json=newTier,proto3" json:"new_tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignPlanResponse) Reset() {
	*x = AssignPlanResponse{}
	mi := &file_subscription_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPlanResponse) ProtoMessage() {}

func (x *AssignPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPlanResponse.ProtoReflect.Descriptor instead.
func (*AssignPlanResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{12}
}

func (x *AssignPlanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AssignPlanResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AssignPlanResponse) GetNewTier() string {
	if x != nil {
		return x.NewTier
	}
	return ""
}

type CreatePaymentIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PlanId        int32                  `protobuf:"varint,2,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentIntentRequest) Reset() {
	*x = CreatePaymentIntentRequest{}
	mi := &file_subscription_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentIntentRequest) ProtoMessage() {}

func (x *CreatePaymentIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentIntentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentIntentRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{13}
}

func (x *CreatePaymentIntentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePaymentIntentRequest) GetPlanId() int32 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

func (x *CreatePaymentIntentRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreatePaymentIntentResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Success              bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code                 int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	ClientSecret         string                 `protobuf:"bytes,3,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	StripeSubscriptionId string                 `protobuf:"bytes,4,opt,name=stripe_subscription_id,json=stripeSubscriptionId,proto3" json:"stripe_subscription_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreatePaymentIntentResponse) Reset() {
	*x = CreatePaymentIntentResponse{}
	mi := &file_subscription_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentIntentResponse) ProtoMessage() {}

func (x *CreatePaymentIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentIntentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentIntentResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{14}
}

func (x *CreatePaymentIntentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreatePaymentIntentResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreatePaymentIntentResponse) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *CreatePaymentIntentResponse) GetStripeSubscriptionId() string {
	if x != nil {
		return x.StripeSubscriptionId
	}
	return ""
}

type HandleStripeWebhookRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Payload         []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	StripeSignature string                 `protobuf:"bytes,2,opt,name=stripe_signature,json=stripeSignature,proto3" json:"stripe_signature,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HandleStripeWebhookRequest) Reset() {
	*x = HandleStripeWebhookRequest{}
	mi := &file_subscription_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleStripeWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleStripeWebhookRequest) ProtoMessage() {}

func (x *HandleStripeWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleStripeWebhookRequest.ProtoReflect.Descriptor instead.
func (*HandleStripeWebhookRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{15}
}

func (x *HandleStripeWebhookRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HandleStripeWebhookRequest) GetStripeSignature() string {
	if x != nil {
		return x.StripeSignature
	}
	return ""
}

type CancelSubscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSubscriptionRequest) Reset() {
	*x = CancelSubscriptionRequest{}
	mi := &file_subscription_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionRequest) ProtoMessage() {}

func (x *CancelSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{16}
}

func (x *CancelSubscriptionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAdminStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdminStatsRequest) Reset() {
	*x = GetAdminStatsRequest{}
	mi := &file_subscription_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdminStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminStatsRequest) ProtoMessage() {}

func (x *GetAdminStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminStatsRequest.ProtoReflect.Descriptor instead.
func (*GetAdminStatsRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{17}
}

type UpdatePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        int32                  `protobuf:"varint,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PriceCents    int32                  `protobuf:"varint,3,opt,name=price_cents,json=priceCents,proto3" json:"price_cents,omitempty"`
	BillingCycle  string                 `protobuf:"bytes,4,opt,name=billing_cycle,json=billingCycle,proto3" json:"billing_cycle,omitempty"`
	StripePriceId string                 `protobuf:"bytes,5,opt,name=stripe_price_id,json=stripePriceId,proto3" json:"stripe_price_id,omitempty"`
	Features      string                 `protobuf:"bytes,6,opt,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePlanRequest) Reset() {
	*x = UpdatePlanRequest{}
	mi := &file_subscription_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePlanRequest) ProtoMessage() {}

func (x *UpdatePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePlanRequest.ProtoReflect.Descriptor instead.
func (*UpdatePlanRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{18}
}

func (x *UpdatePlanRequest) GetPlanId() int32 {
	if x != nil {
		return x.PlanId
	}
	return 0
}

func (x *UpdatePlanRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdatePlanRequest) GetPriceCents() int32 {
	if x != nil {
		return x.PriceCents
	}
	return 0
}

func (x *UpdatePlanRequest) GetBillingCycle() string {
	if x != nil {
		return x.BillingCycle
	}
	return ""
}

func (x *UpdatePlanRequest) GetStripePriceId() string {
	if x != nil {
		return x.StripePriceId
	}
	return ""
}

func (x *UpdatePlanRequest) GetFeatures() string {
	if x != nil {
		return x.Features
	}
	return ""
}

type PlanDistributionEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tier          string                 `protobuf:"bytes,1,opt,name=tier,proto3" json:"tier,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanDistributionEntry) Reset() {
	*x = PlanDistributionEntry{}
	mi := &file_subscription_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanDistributionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanDistributionEntry) ProtoMessage() {}

func (x *PlanDistributionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanDistributionEntry.ProtoReflect.Descriptor instead.
func (*PlanDistributionEntry) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{19}
}

func (x *PlanDistributionEntry) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *PlanDistributionEntry) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MonthlyRevenueEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	RevenueCents  int64                  `protobuf:"varint,2,opt,name=revenue_cents,json=revenueCents,proto3" json:"revenue_cents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlyRevenueEntry) Reset() {
	*x = MonthlyRevenueEntry{}
	mi := &file_subscription_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlyRevenueEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlyRevenueEntry) ProtoMessage() {}

func (x *MonthlyRevenueEntry) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlyRevenueEntry.ProtoReflect.Descriptor instead.
func (*MonthlyRevenueEntry) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{20}
}

func (x *MonthlyRevenueEntry) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *MonthlyRevenueEntry) GetRevenueCents() int64 {
	if x != nil {
		return x.RevenueCents
	}
	return 0
}

type AdminStatsResponse struct {
	state                    protoimpl.MessageState   `protogen:"open.v1"`
	Success                  bool                     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code                     int32                    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	TotalActiveSubscriptions int32                    `protobuf:"varint,3,opt,name=total_active_subscriptions,json=totalActiveSubscriptions,proto3" json:"total_active_subscriptions,omitempty"`
	TotalRevenueCents        int64                    `protobuf:"varint,4,opt,name=total_revenue_cents,json=totalRevenueCents,proto3" json:"total_revenue_cents,omitempty"`
	PlanDistribution         []*PlanDistributionEntry `protobuf:"bytes,5,rep,name=plan_distribution,json=planDistribution,proto3" json:"plan_distribution,omitempty"`
	MonthlyRevenue           []*MonthlyRevenueEntry   `protobuf:"bytes,6,rep,name=monthly_revenue,json=monthlyRevenue,proto3" json:"monthly_revenue,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AdminStatsResponse) Reset() {
	*x = AdminStatsResponse{}
	mi := &file_subscription_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminStatsResponse) ProtoMessage() {}

func (x *AdminStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminStatsResponse.ProtoReflect.Descriptor instead.
func (*AdminStatsResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{21}
}

func (x *AdminStatsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AdminStatsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AdminStatsResponse) GetTotalActiveSubscriptions() int32 {
	if x != nil {
		return x.TotalActiveSubscriptions
	}
	return 0
}

func (x *AdminStatsResponse) GetTotalRevenueCents() int64 {
	if x != nil {
		return x.TotalRevenueCents
	}
	return 0
}

func (x *AdminStatsResponse) GetPlanDistribution() []*PlanDistributionEntry {
	if x != nil {
		return x.PlanDistribution
	}
	return nil
}

func (x *AdminStatsResponse) GetMonthlyRevenue() []*MonthlyRevenueEntry {
	if x != nil {
		return x.MonthlyRevenue
	}
	return nil
}

var File_subscription_proto protoreflect.FileDescriptor

const file_subscription_proto_rawDesc = "" +
	"\n" +
	"\x12subscription.proto\x12\fsubscription\"?\n" +
	"\x0fGenericResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"\xe9\x01\n" +
	"\x04Plan\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\x05R\x06planId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04tier\x18\x03 \x01(\tR\x04tier\x12\x1f\n" +
	"\vprice_cents\x18\x04 \x01(\x05R\n" +
	"priceCents\x12#\n" +
	"\rbilling_cycle\x18\x05 \x01(\tR\fbillingCycle\x12\x1a\n" +
	"\bfeatures\x18\x06 \x01(\tR\bfeatures\x12\x16\n" +
	"\x06active\x18\a \x01(\bR\x06active\x12&\n" +
	"\x0fstripe_price_id\x18\b \x01(\tR\rstripePriceId\"\x9a\x03\n" +
	"\fSubscription\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x17\n" +
	"\aplan_id\x18\x03 \x01(\x05R\x06planId\x12\x12\n" +
	"\x04tier\x18\x04 \x01(\tR\x04tier\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x120\n" +
	"\x14current_period_start\x18\x06 \x01(\tR\x12currentPeriodStart\x12,\n" +
	"\x12current_period_end\x18\a \x01(\tR\x10currentPeriodEnd\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12/\n" +
	"\x14cancel_at_period_end\x18\n" +
	" \x01(\bR\x11cancelAtPeriodEnd\x124\n" +
	"\x16stripe_subscription_id\x18\v \x01(\tR\x14stripeSubscriptionId\"=\n" +
	"\x10ListPlansRequest\x12)\n" +
	"\x10include_inactive\x18\x01 \x01(\bR\x0fincludeInactive\"k\n" +
	"\x11ListPlansResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12(\n" +
	"\x05plans\x18\x03 \x03(\v2\x12.subscription.PlanR\x05plans\")\n" +
	"\x0eGetPlanRequest\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\x05R\x06planId\"g\n" +
	"\x0fGetPlanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12&\n" +
	"\x04plan\x18\x03 \x01(\v2\x12.subscription.PlanR\x04plan\"5\n" +
	"\x1aGetUserSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x8b\x01\n" +
	"\x1bGetUserSubscriptionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12>\n" +
	"\fsubscription\x18\x03 \x01(\v2\x1a.subscription.SubscriptionR\fsubscription\"K\n" +
	"\x18ListSubscriptionsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\xa1\x01\n" +
	"\x19ListSubscriptionsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12@\n" +
	"\rsubscriptions\x18\x03 \x03(\v2\x1a.subscription.SubscriptionR\rsubscriptions\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"E\n" +
	"\x11AssignPlanRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\x05R\x06planId\"]\n" +
	"\x12AssignPlanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x19\n" +
	"\bnew_tier\x18\x03 \x01(\tR\anewTier\"d\n" +
	"\x1aCreatePaymentIntentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aplan_id\x18\x02 \x01(\x05R\x06planId\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\xa6\x01\n" +
	"\x1bCreatePaymentIntentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12#\n" +
	"\rclient_secret\x18\x03 \x01(\tR\fclientSecret\x124\n" +
	"\x16stripe_subscription_id\x18\x04 \x01(\tR\x14stripeSubscriptionId\"a\n" +
	"\x1aHandleStripeWebhookRequest\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12)\n" +
	"\x10stripe_signature\x18\x02 \x01(\tR\x0fstripeSignature\"4\n" +
	"\x19CancelSubscriptionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x16\n" +
	"\x14GetAdminStatsRequest\"\xca\x01\n" +
	"\x11UpdatePlanRequest\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\x05R\x06planId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vprice_cents\x18\x03 \x01(\x05R\n" +
	"priceCents\x12#\n" +
	"\rbilling_cycle\x18\x04 \x01(\tR\fbillingCycle\x12&\n" +
	"\x0fstripe_price_id\x18\x05 \x01(\tR\rstripePriceId\x12\x1a\n" +
	"\bfeatures\x18\x06 \x01(\tR\bfeatures\"A\n" +
	"\x15PlanDistributionEntry\x12\x12\n" +
	"\x04tier\x18\x01 \x01(\tR\x04tier\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"P\n" +
	"\x13MonthlyRevenueEntry\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12#\n" +
	"\rrevenue_cents\x18\x02 \x01(\x03R\frevenueCents\"\xce\x02\n" +
	"\x12AdminStatsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12<\n" +
	"\x1atotal_active_subscriptions\x18\x03 \x01(\x05R\x18totalActiveSubscriptions\x12.\n" +
	"\x13total_revenue_cents\x18\x04 \x01(\x03R\x11totalRevenueCents\x12P\n" +
	"\x11plan_distribution\x18\x05 \x03(\v2#.subscription.PlanDistributionEntryR\x10planDistribution\x12J\n" +
	"\x0fmonthly_revenue\x18\x06 \x03(\v2!.subscription.MonthlyRevenueEntryR\x0emonthlyRevenue2\x9d\a\n" +
	"\x13SubscriptionService\x12L\n" +
	"\tListPlans\x12\x1e.subscription.ListPlansRequest\x1a\x1f.subscription.ListPlansResponse\x12F\n" +
	"\aGetPlan\x12\x1c.subscription.GetPlanRequest\x1a\x1d.subscription.GetPlanResponse\x12j\n" +
	"\x13GetUserSubscription\x12(.subscription.GetUserSubscriptionRequest\x1a).subscription.GetUserSubscriptionResponse\x12d\n" +
	"\x11ListSubscriptions\x12&.subscription.ListSubscriptionsRequest\x1a'.subscription.ListSubscriptionsResponse\x12O\n" +
	"\n" +
	"AssignPlan\x12\x1f.subscription.AssignPlanRequest\x1a .subscription.AssignPlanResponse\x12j\n" +
	"\x13CreatePaymentIntent\x12(.subscription.CreatePaymentIntentRequest\x1a).subscription.CreatePaymentIntentResponse\x12^\n" +
	"\x13HandleStripeWebhook\x12(.subscription.HandleStripeWebhookRequest\x1a\x1d.subscription.GenericResponse\x12\\\n" +
	"\x12CancelSubscription\x12'.subscription.CancelSubscriptionRequest\x1a\x1d.subscription.GenericResponse\x12U\n" +
	"\rGetAdminStats\x12\".subscription.GetAdminStatsRequest\x1a .subscription.AdminStatsResponse\x12L\n" +
	"\n" +
	"UpdatePlan\x12\x1f.subscription.UpdatePlanRequest\x1a\x1d.subscription.GetPlanResponseB*Z(project-devis-subscription/services/grpcb\x06proto3"

var (
	file_subscription_proto_rawDescOnce sync.Once
	file_subscription_proto_rawDescData []byte
)

func file_subscription_proto_rawDescGZIP() []byte {
	file_subscription_proto_rawDescOnce.Do(func() {
		file_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)))
	})
	return file_subscription_proto_rawDescData
}

var file_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_subscription_proto_goTypes = []any{
	(*GenericResponse)(nil),             // 0: subscription.GenericResponse
	(*Plan)(nil),                        // 1: subscription.Plan
	(*Subscription)(nil),                // 2: subscription.Subscription
	(*ListPlansRequest)(nil),            // 3: subscription.ListPlansRequest
	(*ListPlansResponse)(nil),           // 4: subscription.ListPlansResponse
	(*GetPlanRequest)(nil),              // 5: subscription.GetPlanRequest
	(*GetPlanResponse)(nil),             // 6: subscription.GetPlanResponse
	(*GetUserSubscriptionRequest)(nil),  // 7: subscription.GetUserSubscriptionRequest
	(*GetUserSubscriptionResponse)(nil), // 8: subscription.GetUserSubscriptionResponse
	(*ListSubscriptionsRequest)(nil),    // 9: subscription.ListSubscriptionsRequest
	(*ListSubscriptionsResponse)(nil),   // 10: subscription.ListSubscriptionsResponse
	(*AssignPlanRequest)(nil),           // 11: subscription.AssignPlanRequest
	(*AssignPlanResponse)(nil),          // 12: subscription.AssignPlanResponse
	(*CreatePaymentIntentRequest)(nil),  // 13: subscription.CreatePaymentIntentRequest
	(*CreatePaymentIntentResponse)(nil), // 14: subscription.CreatePaymentIntentResponse
	(*HandleStripeWebhookRequest)(nil),  // 15: subscription.HandleStripeWebhookRequest
	(*CancelSubscriptionRequest)(nil),   // 16: subscription.CancelSubscriptionRequest
	(*GetAdminStatsRequest)(nil),        // 17: subscription.GetAdminStatsRequest
	(*UpdatePlanRequest)(nil),           // 18: subscription.UpdatePlanRequest
	(*PlanDistributionEntry)(nil),       // 19: subscription.PlanDistributionEntry
	(*MonthlyRevenueEntry)(nil),         // 20: subscription.MonthlyRevenueEntry
	(*AdminStatsResponse)(nil),          // 21: subscription.AdminStatsResponse
}
var file_subscription_proto_depIdxs = []int32{
	1,  // 0: subscription.ListPlansResponse.plans:type_name -> subscription.Plan
	1,  // 1: subscription.GetPlanResponse.plan:type_name -> subscription.Plan
	2,  // 2: subscription.GetUserSubscriptionResponse.subscription:type_name -> subscription.Subscription
	2,  // 3: subscription.ListSubscriptionsResponse.subscriptions:type_name -> subscription.Subscription
	19, // 4: subscription.AdminStatsResponse.plan_distribution:type_name -> subscription.PlanDistributionEntry
	20, // 5: subscription.AdminStatsResponse.monthly_revenue:type_name -> subscription.MonthlyRevenueEntry
	3,  // 6: subscription.SubscriptionService.ListPlans:input_type -> subscription.ListPlansRequest
	5,  // 7: subscription.SubscriptionService.GetPlan:input_type -> subscription.GetPlanRequest
	7,  // 8: subscription.SubscriptionService.GetUserSubscription:input_type -> subscription.GetUserSubscriptionRequest
	9,  // 9: subscription.SubscriptionService.ListSubscriptions:input_type -> subscription.ListSubscriptionsRequest
	11, // 10: subscription.SubscriptionService.AssignPlan:input_type -> subscription.AssignPlanRequest
	13, // 11: subscription.SubscriptionService.CreatePaymentIntent:input_type -> subscription.CreatePaymentIntentRequest
	15, // 12: subscription.SubscriptionService.HandleStripeWebhook:input_type -> subscription.HandleStripeWebhookRequest
	16, // 13: subscription.SubscriptionService.CancelSubscription:input_type -> subscription.CancelSubscriptionRequest
	17, // 14: subscription.SubscriptionService.GetAdminStats:input_type -> subscription.GetAdminStatsRequest
	18, // 15: subscription.SubscriptionService.UpdatePlan:input_type -> subscription.UpdatePlanRequest
	4,  // 16: subscription.SubscriptionService.ListPlans:output_type -> subscription.ListPlansResponse
	6,  // 17: subscription.SubscriptionService.GetPlan:output_type -> subscription.GetPlanResponse
	8,  // 18: subscription.SubscriptionService.GetUserSubscription:output_type -> subscription.GetUserSubscriptionResponse
	10, // 19: subscription.SubscriptionService.ListSubscriptions:output_type -> subscription.ListSubscriptionsResponse
	12, // 20: subscription.SubscriptionService.AssignPlan:output_type -> subscription.AssignPlanResponse
	14, // 21: subscription.SubscriptionService.CreatePaymentIntent:output_type -> subscription.CreatePaymentIntentResponse
	0,  // 22: subscription.SubscriptionService.HandleStripeWebhook:output_type -> subscription.GenericResponse
	0,  // 23: subscription.SubscriptionService.CancelSubscription:output_type -> subscription.GenericResponse
	21, // 24: subscription.SubscriptionService.GetAdminStats:output_type -> subscription.AdminStatsResponse
	6,  // 25: subscription.SubscriptionService.UpdatePlan:output_type -> subscription.GetPlanResponse
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_subscription_proto_init() }
func file_subscription_proto_init() {
	if File_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subscription_proto_goTypes,
		DependencyIndexes: file_subscription_proto_depIdxs,
		MessageInfos:      file_subscription_proto_msgTypes,
	}.Build()
	File_subscription_proto = out.File
	file_subscription_proto_goTypes = nil
	file_subscription_proto_depIdxs = nil
}
