// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: export.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExportQuoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuoteId       string                 `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportQuoteRequest) Reset() {
	*x = ExportQuoteRequest{}
	mi := &file_export_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportQuoteRequest) ProtoMessage() {}

func (x *ExportQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportQuoteRequest.ProtoReflect.Descriptor instead.
func (*ExportQuoteRequest) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{0}
}

func (x *ExportQuoteRequest) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *ExportQuoteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ExportQuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Pdf           []byte                 `protobuf:"bytes,3,opt,name=pdf,proto3" json:"pdf,omitempty"`
	Filename      string                 `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportQuoteResponse) Reset() {
	*x = ExportQuoteResponse{}
	mi := &file_export_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportQuoteResponse) ProtoMessage() {}

func (x *ExportQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_export_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportQuoteResponse.ProtoReflect.Descriptor instead.
func (*ExportQuoteResponse) Descriptor() ([]byte, []int) {
	return file_export_proto_rawDescGZIP(), []int{1}
}

func (x *ExportQuoteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExportQuoteResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ExportQuoteResponse) GetPdf() []byte {
	if x != nil {
		return x.Pdf
	}
	return nil
}

func (x *ExportQuoteResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

var File_export_proto protoreflect.FileDescriptor

const file_export_proto_rawDesc = "" +
	"\n" +
	"\fexport.proto\x12\x06export\"H\n" +
	"\x12ExportQuoteRequest\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"q\n" +
	"\x13ExportQuoteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x10\n" +
	"\x03pdf\x18\x03 \x01(\fR\x03pdf\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilename2W\n" +
	"\rExportService\x12F\n" +
	"\vExportQuote\x12\x1a.export.ExportQuoteRequest\x1a\x1b.export.ExportQuoteResponseB$Z\"project-devis-export/services/grpcb\x06proto3"

var (
	file_export_proto_rawDescOnce sync.Once
	file_export_proto_rawDescData []byte
)

func file_export_proto_rawDescGZIP() []byte {
	file_export_proto_rawDescOnce.Do(func() {
		file_export_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_export_proto_rawDesc), len(file_export_proto_rawDesc)))
	})
	return file_export_proto_rawDescData
}

var file_export_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_export_proto_goTypes = []any{
	(*ExportQuoteRequest)(nil),  // 0: export.ExportQuoteRequest
	(*ExportQuoteResponse)(nil), // 1: export.ExportQuoteResponse
}
var file_export_proto_depIdxs = []int32{
	0, // 0: export.ExportService.ExportQuote:input_type -> export.ExportQuoteRequest
	1, // 1: export.ExportService.ExportQuote:output_type -> export.ExportQuoteResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_export_proto_init() }
func file_export_proto_init() {
	if File_export_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_export_proto_rawDesc), len(file_export_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_export_proto_goTypes,
		DependencyIndexes: file_export_proto_depIdxs,
		MessageInfos:      file_export_proto_msgTypes,
	}.Build()
	File_export_proto = out.File
	file_export_proto_goTypes = nil
	file_export_proto_depIdxs = nil
}
