// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: services/user_auth/user_auth.proto

package user_auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InsertUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertUserRequest) Reset() {
	*x = InsertUserRequest{}
	mi := &file_services_user_auth_user_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertUserRequest) ProtoMessage() {}

func (x *InsertUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_auth_user_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertUserRequest.ProtoReflect.Descriptor instead.
func (*InsertUserRequest) Descriptor() ([]byte, []int) {
	return file_services_user_auth_user_auth_proto_rawDescGZIP(), []int{0}
}

func (x *InsertUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InsertUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type InsertUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertUserResponse) Reset() {
	*x = InsertUserResponse{}
	mi := &file_services_user_auth_user_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertUserResponse) ProtoMessage() {}

func (x *InsertUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_auth_user_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertUserResponse.ProtoReflect.Descriptor instead.
func (*InsertUserResponse) Descriptor() ([]byte, []int) {
	return file_services_user_auth_user_auth_proto_rawDescGZIP(), []int{1}
}

func (x *InsertUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InsertUserResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InsertUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_services_user_auth_user_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_auth_user_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_services_user_auth_user_auth_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GenericResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenericResponse) Reset() {
	*x = GenericResponse{}
	mi := &file_services_user_auth_user_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenericResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericResponse) ProtoMessage() {}

func (x *GenericResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_user_auth_user_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericResponse.ProtoReflect.Descriptor instead.
func (*GenericResponse) Descriptor() ([]byte, []int) {
	return file_services_user_auth_user_auth_proto_rawDescGZIP(), []int{3}
}

func (x *GenericResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GenericResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_services_user_auth_user_auth_proto protoreflect.FileDescriptor

const file_services_user_auth_user_auth_proto_rawDesc = "" +
	"\n" +
	"\"services/user_auth/user_auth.proto\x12\tuser_auth\"E\n" +
	"\x11InsertUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"[\n" +
	"\x12InsertUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"?\n" +
	"\x0fGenericResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code2\xa4\x01\n" +
	"\x0fAuthUserService\x12I\n" +
	"\n" +
	"InsertUser\x12\x1c.user_auth.InsertUserRequest\x1a\x1d.user_auth.InsertUserResponse\x12F\n" +
	"\n" +
	"DeleteUser\x12\x1c.user_auth.DeleteUserRequest\x1a\x1a.user_auth.GenericResponseB'Z%project-devis-auth/services/user_authb\x06proto3"

var (
	file_services_user_auth_user_auth_proto_rawDescOnce sync.Once
	file_services_user_auth_user_auth_proto_rawDescData []byte
)

func file_services_user_auth_user_auth_proto_rawDescGZIP() []byte {
	file_services_user_auth_user_auth_proto_rawDescOnce.Do(func() {
		file_services_user_auth_user_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_user_auth_user_auth_proto_rawDesc), len(file_services_user_auth_user_auth_proto_rawDesc)))
	})
	return file_services_user_auth_user_auth_proto_rawDescData
}

var file_services_user_auth_user_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_user_auth_user_auth_proto_goTypes = []any{
	(*InsertUserRequest)(nil),  // 0: user_auth.InsertUserRequest
	(*InsertUserResponse)(nil), // 1: user_auth.InsertUserResponse
	(*DeleteUserRequest)(nil),  // 2: user_auth.DeleteUserRequest
	(*GenericResponse)(nil),    // 3: user_auth.GenericResponse
}
var file_services_user_auth_user_auth_proto_depIdxs = []int32{
	0, // 0: user_auth.AuthUserService.InsertUser:input_type -> user_auth.InsertUserRequest
	2, // 1: user_auth.AuthUserService.DeleteUser:input_type -> user_auth.DeleteUserRequest
	1, // 2: user_auth.AuthUserService.InsertUser:output_type -> user_auth.InsertUserResponse
	3, // 3: user_auth.AuthUserService.DeleteUser:output_type -> user_auth.GenericResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_user_auth_user_auth_proto_init() }
func file_services_user_auth_user_auth_proto_init() {
	if File_services_user_auth_user_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_user_auth_user_auth_proto_rawDesc), len(file_services_user_auth_user_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_user_auth_user_auth_proto_goTypes,
		DependencyIndexes: file_services_user_auth_user_auth_proto_depIdxs,
		MessageInfos:      file_services_user_auth_user_auth_proto_msgTypes,
	}.Build()
	File_services_user_auth_user_auth_proto = out.File
	file_services_user_auth_user_auth_proto_goTypes = nil
	file_services_user_auth_user_auth_proto_depIdxs = nil
}
