// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: invoice.proto

package invoice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InvoiceService_CreateInvoiceFromSchedule_FullMethodName  = "/invoice.InvoiceService/CreateInvoiceFromSchedule"
	InvoiceService_CreateInvoiceFromQuote_FullMethodName     = "/invoice.InvoiceService/CreateInvoiceFromQuote"
	InvoiceService_IssueInvoice_FullMethodName               = "/invoice.InvoiceService/IssueInvoice"
	InvoiceService_MarkInvoicePaid_FullMethodName            = "/invoice.InvoiceService/MarkInvoicePaid"
	InvoiceService_DeleteDraftInvoice_FullMethodName         = "/invoice.InvoiceService/DeleteDraftInvoice"
	InvoiceService_GetInvoice_FullMethodName                 = "/invoice.InvoiceService/GetInvoice"
	InvoiceService_ListInvoices_FullMethodName               = "/invoice.InvoiceService/ListInvoices"
	InvoiceService_CreateCreditNote_FullMethodName           = "/invoice.InvoiceService/CreateCreditNote"
	InvoiceService_GetCreditNote_FullMethodName              = "/invoice.InvoiceService/GetCreditNote"
	InvoiceService_ListCreditNotes_FullMethodName            = "/invoice.InvoiceService/ListCreditNotes"
	InvoiceService_VerifyChain_FullMethodName                = "/invoice.InvoiceService/VerifyChain"
	InvoiceService_GetOSSThresholdStatus_FullMethodName      = "/invoice.InvoiceService/GetOSSThresholdStatus"
	InvoiceService_SetInvoiceLifecycleStatus_FullMethodName  = "/invoice.InvoiceService/SetInvoiceLifecycleStatus"
	InvoiceService_ListInvoiceLifecycleEvents_FullMethodName = "/invoice.InvoiceService/ListInvoiceLifecycleEvents"
)

// InvoiceServiceClient is the client API for InvoiceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InvoiceServiceClient interface {
	CreateInvoiceFromSchedule(ctx context.Context, in *CreateInvoiceFromScheduleRequest, opts ...grpc.CallOption) (*CreateInvoiceResponse, error)
	CreateInvoiceFromQuote(ctx context.Context, in *CreateInvoiceFromQuoteRequest, opts ...grpc.CallOption) (*CreateInvoiceResponse, error)
	IssueInvoice(ctx context.Context, in *IssueInvoiceRequest, opts ...grpc.CallOption) (*CreateInvoiceResponse, error)
	MarkInvoicePaid(ctx context.Context, in *MarkInvoicePaidRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	// Delete a still-unissued invoice. Allowed only while DRAFT (no number, no
	// snapshot, no seal); an issued invoice stays immutable.
	DeleteDraftInvoice(ctx context.Context, in *DeleteDraftInvoiceRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	GetInvoice(ctx context.Context, in *GetInvoiceRequest, opts ...grpc.CallOption) (*GetInvoiceResponse, error)
	ListInvoices(ctx context.Context, in *ListInvoicesRequest, opts ...grpc.CallOption) (*ListInvoicesResponse, error)
	// Credit notes (avoirs). Crediting replaces invoice cancellation: it
	// neutralises part or all of an issued invoice without changing its status.
	CreateCreditNote(ctx context.Context, in *CreateCreditNoteRequest, opts ...grpc.CallOption) (*CreateCreditNoteResponse, error)
	GetCreditNote(ctx context.Context, in *GetCreditNoteRequest, opts ...grpc.CallOption) (*GetCreditNoteResponse, error)
	ListCreditNotes(ctx context.Context, in *ListCreditNotesRequest, opts ...grpc.CallOption) (*ListCreditNotesResponse, error)
	// Inalterability: recompute and verify the issuer's seal chain.
	VerifyChain(ctx context.Context, in *VerifyChainRequest, opts ...grpc.CallOption) (*VerifyChainResponse, error)
	// OSS distance-selling threshold status for the current civil year: where the
	// issuer stands against the EUR 10 000 threshold (art. 259 D CGI).
	GetOSSThresholdStatus(ctx context.Context, in *GetOSSThresholdStatusRequest, opts ...grpc.CallOption) (*GetOSSThresholdStatusResponse, error)
	// E-invoicing lifecycle (réforme FR B2B). Orthogonal to the business status:
	// tracks the invoice on the platform (déposée/reçue/approuvée/refusée/encaissée).
	// Manual issuer-driven transitions for now; platform auto-feed comes in B6.
	SetInvoiceLifecycleStatus(ctx context.Context, in *SetInvoiceLifecycleStatusRequest, opts ...grpc.CallOption) (*GenericResponse, error)
	ListInvoiceLifecycleEvents(ctx context.Context, in *ListInvoiceLifecycleEventsRequest, opts ...grpc.CallOption) (*ListInvoiceLifecycleEventsResponse, error)
}

type invoiceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInvoiceServiceClient(cc grpc.ClientConnInterface) InvoiceServiceClient {
	return &invoiceServiceClient{cc}
}

func (c *invoiceServiceClient) CreateInvoiceFromSchedule(ctx context.Context, in *CreateInvoiceFromScheduleRequest, opts ...grpc.CallOption) (*CreateInvoiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInvoiceResponse)
	err := c.cc.Invoke(ctx, InvoiceService_CreateInvoiceFromSchedule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invoiceServiceClient) CreateInvoiceFromQuote(ctx context.Context, in *CreateInvoiceFromQuoteRequest, opts ...grpc.CallOption) (*CreateInvoiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInvoiceResponse)
	err := c.cc.Invoke(ctx, InvoiceService_CreateInvoiceFromQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invoiceServiceClient) IssueInvoice(ctx context.Context, in *IssueInvoiceRequest, opts ...grpc.CallOption) (*CreateInvoiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInvoiceResponse)
	err := c.cc.Invoke(ctx, InvoiceService_IssueInvoice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invoiceServiceClient) MarkInvoicePaid(ctx context.Context, in *MarkInvoicePaidRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, InvoiceService_MarkInvoicePaid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invoiceServiceClient) DeleteDraftInvoice(ctx context.Context, in *DeleteDraftInvoiceRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, InvoiceService_DeleteDraftInvoice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invoiceServiceClient) GetInvoice(ctx context.Context, in *GetInvoiceRequest, opts ...grpc.CallOption) (*GetInvoiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInvoiceResponse)
	err := c.cc.Invoke(ctx, InvoiceService_GetInvoice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invoiceServiceClient) ListInvoices(ctx context.Context, in *ListInvoicesRequest, opts ...grpc.CallOption) (*ListInvoicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInvoicesResponse)
	err := c.cc.Invoke(ctx, InvoiceService_ListInvoices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invoiceServiceClient) CreateCreditNote(ctx context.Context, in *CreateCreditNoteRequest, opts ...grpc.CallOption) (*CreateCreditNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCreditNoteResponse)
	err := c.cc.Invoke(ctx, InvoiceService_CreateCreditNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invoiceServiceClient) GetCreditNote(ctx context.Context, in *GetCreditNoteRequest, opts ...grpc.CallOption) (*GetCreditNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCreditNoteResponse)
	err := c.cc.Invoke(ctx, InvoiceService_GetCreditNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invoiceServiceClient) ListCreditNotes(ctx context.Context, in *ListCreditNotesRequest, opts ...grpc.CallOption) (*ListCreditNotesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCreditNotesResponse)
	err := c.cc.Invoke(ctx, InvoiceService_ListCreditNotes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invoiceServiceClient) VerifyChain(ctx context.Context, in *VerifyChainRequest, opts ...grpc.CallOption) (*VerifyChainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyChainResponse)
	err := c.cc.Invoke(ctx, InvoiceService_VerifyChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invoiceServiceClient) GetOSSThresholdStatus(ctx context.Context, in *GetOSSThresholdStatusRequest, opts ...grpc.CallOption) (*GetOSSThresholdStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOSSThresholdStatusResponse)
	err := c.cc.Invoke(ctx, InvoiceService_GetOSSThresholdStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invoiceServiceClient) SetInvoiceLifecycleStatus(ctx context.Context, in *SetInvoiceLifecycleStatusRequest, opts ...grpc.CallOption) (*GenericResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenericResponse)
	err := c.cc.Invoke(ctx, InvoiceService_SetInvoiceLifecycleStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invoiceServiceClient) ListInvoiceLifecycleEvents(ctx context.Context, in *ListInvoiceLifecycleEventsRequest, opts ...grpc.CallOption) (*ListInvoiceLifecycleEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInvoiceLifecycleEventsResponse)
	err := c.cc.Invoke(ctx, InvoiceService_ListInvoiceLifecycleEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvoiceServiceServer is the server API for InvoiceService service.
// All implementations must embed UnimplementedInvoiceServiceServer
// for forward compatibility.
type InvoiceServiceServer interface {
	CreateInvoiceFromSchedule(context.Context, *CreateInvoiceFromScheduleRequest) (*CreateInvoiceResponse, error)
	CreateInvoiceFromQuote(context.Context, *CreateInvoiceFromQuoteRequest) (*CreateInvoiceResponse, error)
	IssueInvoice(context.Context, *IssueInvoiceRequest) (*CreateInvoiceResponse, error)
	MarkInvoicePaid(context.Context, *MarkInvoicePaidRequest) (*GenericResponse, error)
	// Delete a still-unissued invoice. Allowed only while DRAFT (no number, no
	// snapshot, no seal); an issued invoice stays immutable.
	DeleteDraftInvoice(context.Context, *DeleteDraftInvoiceRequest) (*GenericResponse, error)
	GetInvoice(context.Context, *GetInvoiceRequest) (*GetInvoiceResponse, error)
	ListInvoices(context.Context, *ListInvoicesRequest) (*ListInvoicesResponse, error)
	// Credit notes (avoirs). Crediting replaces invoice cancellation: it
	// neutralises part or all of an issued invoice without changing its status.
	CreateCreditNote(context.Context, *CreateCreditNoteRequest) (*CreateCreditNoteResponse, error)
	GetCreditNote(context.Context, *GetCreditNoteRequest) (*GetCreditNoteResponse, error)
	ListCreditNotes(context.Context, *ListCreditNotesRequest) (*ListCreditNotesResponse, error)
	// Inalterability: recompute and verify the issuer's seal chain.
	VerifyChain(context.Context, *VerifyChainRequest) (*VerifyChainResponse, error)
	// OSS distance-selling threshold status for the current civil year: where the
	// issuer stands against the EUR 10 000 threshold (art. 259 D CGI).
	GetOSSThresholdStatus(context.Context, *GetOSSThresholdStatusRequest) (*GetOSSThresholdStatusResponse, error)
	// E-invoicing lifecycle (réforme FR B2B). Orthogonal to the business status:
	// tracks the invoice on the platform (déposée/reçue/approuvée/refusée/encaissée).
	// Manual issuer-driven transitions for now; platform auto-feed comes in B6.
	SetInvoiceLifecycleStatus(context.Context, *SetInvoiceLifecycleStatusRequest) (*GenericResponse, error)
	ListInvoiceLifecycleEvents(context.Context, *ListInvoiceLifecycleEventsRequest) (*ListInvoiceLifecycleEventsResponse, error)
	mustEmbedUnimplementedInvoiceServiceServer()
}

// UnimplementedInvoiceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInvoiceServiceServer struct{}

func (UnimplementedInvoiceServiceServer) CreateInvoiceFromSchedule(context.Context, *CreateInvoiceFromScheduleRequest) (*CreateInvoiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInvoiceFromSchedule not implemented")
}
func (UnimplementedInvoiceServiceServer) CreateInvoiceFromQuote(context.Context, *CreateInvoiceFromQuoteRequest) (*CreateInvoiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInvoiceFromQuote not implemented")
}
func (UnimplementedInvoiceServiceServer) IssueInvoice(context.Context, *IssueInvoiceRequest) (*CreateInvoiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueInvoice not implemented")
}
func (UnimplementedInvoiceServiceServer) MarkInvoicePaid(context.Context, *MarkInvoicePaidRequest) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkInvoicePaid not implemented")
}
func (UnimplementedInvoiceServiceServer) DeleteDraftInvoice(context.Context, *DeleteDraftInvoiceRequest) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDraftInvoice not implemented")
}
func (UnimplementedInvoiceServiceServer) GetInvoice(context.Context, *GetInvoiceRequest) (*GetInvoiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInvoice not implemented")
}
func (UnimplementedInvoiceServiceServer) ListInvoices(context.Context, *ListInvoicesRequest) (*ListInvoicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInvoices not implemented")
}
func (UnimplementedInvoiceServiceServer) CreateCreditNote(context.Context, *CreateCreditNoteRequest) (*CreateCreditNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCreditNote not implemented")
}
func (UnimplementedInvoiceServiceServer) GetCreditNote(context.Context, *GetCreditNoteRequest) (*GetCreditNoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCreditNote not implemented")
}
func (UnimplementedInvoiceServiceServer) ListCreditNotes(context.Context, *ListCreditNotesRequest) (*ListCreditNotesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCreditNotes not implemented")
}
func (UnimplementedInvoiceServiceServer) VerifyChain(context.Context, *VerifyChainRequest) (*VerifyChainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyChain not implemented")
}
func (UnimplementedInvoiceServiceServer) GetOSSThresholdStatus(context.Context, *GetOSSThresholdStatusRequest) (*GetOSSThresholdStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOSSThresholdStatus not implemented")
}
func (UnimplementedInvoiceServiceServer) SetInvoiceLifecycleStatus(context.Context, *SetInvoiceLifecycleStatusRequest) (*GenericResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetInvoiceLifecycleStatus not implemented")
}
func (UnimplementedInvoiceServiceServer) ListInvoiceLifecycleEvents(context.Context, *ListInvoiceLifecycleEventsRequest) (*ListInvoiceLifecycleEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInvoiceLifecycleEvents not implemented")
}
func (UnimplementedInvoiceServiceServer) mustEmbedUnimplementedInvoiceServiceServer() {}
func (UnimplementedInvoiceServiceServer) testEmbeddedByValue()                        {}

// UnsafeInvoiceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InvoiceServiceServer will
// result in compilation errors.
type UnsafeInvoiceServiceServer interface {
	mustEmbedUnimplementedInvoiceServiceServer()
}

func RegisterInvoiceServiceServer(s grpc.ServiceRegistrar, srv InvoiceServiceServer) {
	// If the following call panics, it indicates UnimplementedInvoiceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InvoiceService_ServiceDesc, srv)
}

func _InvoiceService_CreateInvoiceFromSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInvoiceFromScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceServiceServer).CreateInvoiceFromSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvoiceService_CreateInvoiceFromSchedule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceServiceServer).CreateInvoiceFromSchedule(ctx, req.(*CreateInvoiceFromScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvoiceService_CreateInvoiceFromQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInvoiceFromQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceServiceServer).CreateInvoiceFromQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvoiceService_CreateInvoiceFromQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceServiceServer).CreateInvoiceFromQuote(ctx, req.(*CreateInvoiceFromQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvoiceService_IssueInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceServiceServer).IssueInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvoiceService_IssueInvoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceServiceServer).IssueInvoice(ctx, req.(*IssueInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvoiceService_MarkInvoicePaid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkInvoicePaidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceServiceServer).MarkInvoicePaid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvoiceService_MarkInvoicePaid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceServiceServer).MarkInvoicePaid(ctx, req.(*MarkInvoicePaidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvoiceService_DeleteDraftInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDraftInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceServiceServer).DeleteDraftInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvoiceService_DeleteDraftInvoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceServiceServer).DeleteDraftInvoice(ctx, req.(*DeleteDraftInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvoiceService_GetInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInvoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceServiceServer).GetInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvoiceService_GetInvoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceServiceServer).GetInvoice(ctx, req.(*GetInvoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvoiceService_ListInvoices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInvoicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceServiceServer).ListInvoices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvoiceService_ListInvoices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceServiceServer).ListInvoices(ctx, req.(*ListInvoicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvoiceService_CreateCreditNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCreditNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceServiceServer).CreateCreditNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvoiceService_CreateCreditNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceServiceServer).CreateCreditNote(ctx, req.(*CreateCreditNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvoiceService_GetCreditNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCreditNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceServiceServer).GetCreditNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvoiceService_GetCreditNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceServiceServer).GetCreditNote(ctx, req.(*GetCreditNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvoiceService_ListCreditNotes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCreditNotesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceServiceServer).ListCreditNotes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvoiceService_ListCreditNotes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceServiceServer).ListCreditNotes(ctx, req.(*ListCreditNotesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvoiceService_VerifyChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceServiceServer).VerifyChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvoiceService_VerifyChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceServiceServer).VerifyChain(ctx, req.(*VerifyChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvoiceService_GetOSSThresholdStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOSSThresholdStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceServiceServer).GetOSSThresholdStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvoiceService_GetOSSThresholdStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceServiceServer).GetOSSThresholdStatus(ctx, req.(*GetOSSThresholdStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvoiceService_SetInvoiceLifecycleStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetInvoiceLifecycleStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceServiceServer).SetInvoiceLifecycleStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvoiceService_SetInvoiceLifecycleStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceServiceServer).SetInvoiceLifecycleStatus(ctx, req.(*SetInvoiceLifecycleStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvoiceService_ListInvoiceLifecycleEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInvoiceLifecycleEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceServiceServer).ListInvoiceLifecycleEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InvoiceService_ListInvoiceLifecycleEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceServiceServer).ListInvoiceLifecycleEvents(ctx, req.(*ListInvoiceLifecycleEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InvoiceService_ServiceDesc is the grpc.ServiceDesc for InvoiceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InvoiceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "invoice.InvoiceService",
	HandlerType: (*InvoiceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateInvoiceFromSchedule",
			Handler:    _InvoiceService_CreateInvoiceFromSchedule_Handler,
		},
		{
			MethodName: "CreateInvoiceFromQuote",
			Handler:    _InvoiceService_CreateInvoiceFromQuote_Handler,
		},
		{
			MethodName: "IssueInvoice",
			Handler:    _InvoiceService_IssueInvoice_Handler,
		},
		{
			MethodName: "MarkInvoicePaid",
			Handler:    _InvoiceService_MarkInvoicePaid_Handler,
		},
		{
			MethodName: "DeleteDraftInvoice",
			Handler:    _InvoiceService_DeleteDraftInvoice_Handler,
		},
		{
			MethodName: "GetInvoice",
			Handler:    _InvoiceService_GetInvoice_Handler,
		},
		{
			MethodName: "ListInvoices",
			Handler:    _InvoiceService_ListInvoices_Handler,
		},
		{
			MethodName: "CreateCreditNote",
			Handler:    _InvoiceService_CreateCreditNote_Handler,
		},
		{
			MethodName: "GetCreditNote",
			Handler:    _InvoiceService_GetCreditNote_Handler,
		},
		{
			MethodName: "ListCreditNotes",
			Handler:    _InvoiceService_ListCreditNotes_Handler,
		},
		{
			MethodName: "VerifyChain",
			Handler:    _InvoiceService_VerifyChain_Handler,
		},
		{
			MethodName: "GetOSSThresholdStatus",
			Handler:    _InvoiceService_GetOSSThresholdStatus_Handler,
		},
		{
			MethodName: "SetInvoiceLifecycleStatus",
			Handler:    _InvoiceService_SetInvoiceLifecycleStatus_Handler,
		},
		{
			MethodName: "ListInvoiceLifecycleEvents",
			Handler:    _InvoiceService_ListInvoiceLifecycleEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "invoice.proto",
}
